//! Bulk operations for AttendanceClock entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateAttendanceClockDto;
use crate::application::service::AttendanceClockService;
use crate::domain::entity::AttendanceClock;

/// Bulk operation handler for AttendanceClock entities.
///
/// Wraps `AttendanceClockService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type AttendanceClockBulkService = GenericBulkService<AttendanceClock, CreateAttendanceClockDto, AttendanceClockService>;

// <<< CUSTOM
// END CUSTOM
