//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod attendance_bulk;
pub mod attendance_clock_bulk;

pub use attendance_bulk::AttendanceBulkService;
pub use attendance_clock_bulk::AttendanceClockBulkService;

// <<< CUSTOM
// END CUSTOM
