//! AttendanceSession DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::AttendanceSession;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::PunchSource;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new AttendanceSession
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateAttendanceSessionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub date: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "check_in")]
    pub check_in: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "check_out")]
    pub check_out: Option<DateTime<Utc>>,
    pub source: PunchSource,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "correction_reason")]
    pub correction_reason: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a AttendanceSession
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateAttendanceSessionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub date: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "check_in")]
    pub check_in: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "check_out")]
    pub check_out: Option<DateTime<Utc>>,
    pub source: PunchSource,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "correction_reason")]
    pub correction_reason: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a AttendanceSession
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchAttendanceSessionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub date: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "check_in")]
    pub check_in: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "check_out")]
    pub check_out: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source: Option<PunchSource>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "correction_reason")]
    pub correction_reason: Option<String>,
}

impl PatchAttendanceSessionDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.employee_id.is_some() || self.date.is_some() || self.check_in.is_some() || self.check_out.is_some() || self.source.is_some() || self.correction_reason.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for AttendanceSession entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AttendanceSessionResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub date: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub check_in: DateTime<Utc>,
    pub check_out: Option<DateTime<Utc>>,
    pub source: PunchSource,
    pub correction_reason: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for AttendanceSession entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AttendanceSessionListResponseDto {
    /// List of items
    pub items: Vec<AttendanceSessionResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl AttendanceSessionListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<AttendanceSessionResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AttendanceSessionSummaryDto {
    pub id: Uuid,
    pub employee_id: Uuid,
    pub date: NaiveDate,
    pub check_in: DateTime<Utc>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<AttendanceSession> for AttendanceSessionResponseDto {
    fn from(entity: AttendanceSession) -> Self {
        Self {
            id: entity.id,
            employee_id: entity.employee_id,
            date: entity.date,
            check_in: entity.check_in,
            check_out: entity.check_out,
            source: entity.source,
            correction_reason: entity.correction_reason,
            metadata: entity.metadata,
        }
    }
}

impl From<AttendanceSession> for AttendanceSessionSummaryDto {
    fn from(entity: AttendanceSession) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            employee_id: entity.employee_id,
            date: entity.date,
            check_in: entity.check_in,
            created_at,
        }
    }
}

impl From<CreateAttendanceSessionDto> for AttendanceSession {
    fn from(dto: CreateAttendanceSessionDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            employee_id: dto.employee_id,
            date: dto.date,
            check_in: dto.check_in,
            check_out: dto.check_out,
            source: dto.source,
            correction_reason: dto.correction_reason,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&AttendanceSession> for AttendanceSessionResponseDto {
    fn from(entity: &AttendanceSession) -> Self {
        Self {
            id: entity.id.clone(),
            employee_id: entity.employee_id.clone(),
            date: entity.date.clone(),
            check_in: entity.check_in.clone(),
            check_out: entity.check_out.clone(),
            source: entity.source.clone(),
            correction_reason: entity.correction_reason.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateAttendanceSessionDto> for AttendanceSession {
    fn from_create_dto(dto: CreateAttendanceSessionDto) -> backbone_core::ServiceResult<Self> {
        Ok(AttendanceSession::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateAttendanceSessionDto> for AttendanceSession {
    fn apply_update(mut self, dto: UpdateAttendanceSessionDto) -> backbone_core::ServiceResult<Self> {
        self.employee_id = dto.employee_id;
        self.date = dto.date;
        self.check_in = dto.check_in;
        self.check_out = dto.check_out;
        self.source = dto.source;
        self.correction_reason = dto.correction_reason;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to AttendanceSession here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
