//! AttendanceClock DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::AttendanceClock;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::PunchDirection;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new AttendanceClock
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateAttendanceClockDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "session_id")]
    pub session_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub date: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "punched_at")]
    pub punched_at: DateTime<Utc>,
    pub direction: PunchDirection,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a AttendanceClock
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateAttendanceClockDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "session_id")]
    pub session_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub date: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "punched_at")]
    pub punched_at: DateTime<Utc>,
    pub direction: PunchDirection,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a AttendanceClock
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchAttendanceClockDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "session_id")]
    pub session_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub date: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "punched_at")]
    pub punched_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub direction: Option<PunchDirection>,
}

impl PatchAttendanceClockDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.session_id.is_some() || self.employee_id.is_some() || self.date.is_some() || self.punched_at.is_some() || self.direction.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for AttendanceClock entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AttendanceClockResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub session_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub date: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub punched_at: DateTime<Utc>,
    pub direction: PunchDirection,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for AttendanceClock entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AttendanceClockListResponseDto {
    /// List of items
    pub items: Vec<AttendanceClockResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl AttendanceClockListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<AttendanceClockResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AttendanceClockSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub session_id: Uuid,
    pub employee_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<AttendanceClock> for AttendanceClockResponseDto {
    fn from(entity: AttendanceClock) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            session_id: entity.session_id,
            employee_id: entity.employee_id,
            date: entity.date,
            punched_at: entity.punched_at,
            direction: entity.direction,
            metadata: entity.metadata,
        }
    }
}

impl From<AttendanceClock> for AttendanceClockSummaryDto {
    fn from(entity: AttendanceClock) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            session_id: entity.session_id,
            employee_id: entity.employee_id,
            created_at,
        }
    }
}

impl From<CreateAttendanceClockDto> for AttendanceClock {
    fn from(dto: CreateAttendanceClockDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            session_id: dto.session_id,
            employee_id: dto.employee_id,
            date: dto.date,
            punched_at: dto.punched_at,
            direction: dto.direction,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&AttendanceClock> for AttendanceClockResponseDto {
    fn from(entity: &AttendanceClock) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            session_id: entity.session_id.clone(),
            employee_id: entity.employee_id.clone(),
            date: entity.date.clone(),
            punched_at: entity.punched_at.clone(),
            direction: entity.direction.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateAttendanceClockDto> for AttendanceClock {
    fn from_create_dto(dto: CreateAttendanceClockDto) -> backbone_core::ServiceResult<Self> {
        Ok(AttendanceClock::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateAttendanceClockDto> for AttendanceClock {
    fn apply_update(mut self, dto: UpdateAttendanceClockDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.session_id = dto.session_id;
        self.employee_id = dto.employee_id;
        self.date = dto.date;
        self.punched_at = dto.punched_at;
        self.direction = dto.direction;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to AttendanceClock here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

