//! AttendanceCorrection DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::AttendanceCorrection;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::CorrectionStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new AttendanceCorrection
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateAttendanceCorrectionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "session_id")]
    pub session_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "check_in")]
    pub check_in: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "check_out")]
    pub check_out: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub reason: String,
    pub status: CorrectionStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "approval_request_id")]
    pub approval_request_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "submitted_at")]
    pub submitted_at: DateTime<Utc>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a AttendanceCorrection
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateAttendanceCorrectionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "session_id")]
    pub session_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "check_in")]
    pub check_in: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "check_out")]
    pub check_out: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub reason: String,
    pub status: CorrectionStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "approval_request_id")]
    pub approval_request_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "submitted_at")]
    pub submitted_at: DateTime<Utc>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a AttendanceCorrection
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchAttendanceCorrectionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "session_id")]
    pub session_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "check_in")]
    pub check_in: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "check_out")]
    pub check_out: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<CorrectionStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "approval_request_id")]
    pub approval_request_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "submitted_at")]
    pub submitted_at: Option<DateTime<Utc>>,
}

impl PatchAttendanceCorrectionDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.session_id.is_some() || self.employee_id.is_some() || self.check_in.is_some() || self.check_out.is_some() || self.reason.is_some() || self.status.is_some() || self.approval_request_id.is_some() || self.submitted_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for AttendanceCorrection entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AttendanceCorrectionResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub session_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub check_in: DateTime<Utc>,
    pub check_out: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub reason: String,
    pub status: CorrectionStatus,
    pub approval_request_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub submitted_at: DateTime<Utc>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for AttendanceCorrection entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AttendanceCorrectionListResponseDto {
    /// List of items
    pub items: Vec<AttendanceCorrectionResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl AttendanceCorrectionListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<AttendanceCorrectionResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AttendanceCorrectionSummaryDto {
    pub id: Uuid,
    pub session_id: Uuid,
    pub employee_id: Uuid,
    pub check_in: DateTime<Utc>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<AttendanceCorrection> for AttendanceCorrectionResponseDto {
    fn from(entity: AttendanceCorrection) -> Self {
        Self {
            id: entity.id,
            session_id: entity.session_id,
            employee_id: entity.employee_id,
            check_in: entity.check_in,
            check_out: entity.check_out,
            reason: entity.reason,
            status: entity.status,
            approval_request_id: entity.approval_request_id,
            submitted_at: entity.submitted_at,
            metadata: entity.metadata,
        }
    }
}

impl From<AttendanceCorrection> for AttendanceCorrectionSummaryDto {
    fn from(entity: AttendanceCorrection) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            session_id: entity.session_id,
            employee_id: entity.employee_id,
            check_in: entity.check_in,
            created_at,
        }
    }
}

impl From<CreateAttendanceCorrectionDto> for AttendanceCorrection {
    fn from(dto: CreateAttendanceCorrectionDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            session_id: dto.session_id,
            employee_id: dto.employee_id,
            check_in: dto.check_in,
            check_out: dto.check_out,
            reason: dto.reason,
            status: dto.status,
            approval_request_id: dto.approval_request_id,
            submitted_at: dto.submitted_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&AttendanceCorrection> for AttendanceCorrectionResponseDto {
    fn from(entity: &AttendanceCorrection) -> Self {
        Self {
            id: entity.id.clone(),
            session_id: entity.session_id.clone(),
            employee_id: entity.employee_id.clone(),
            check_in: entity.check_in.clone(),
            check_out: entity.check_out.clone(),
            reason: entity.reason.clone(),
            status: entity.status.clone(),
            approval_request_id: entity.approval_request_id.clone(),
            submitted_at: entity.submitted_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateAttendanceCorrectionDto> for AttendanceCorrection {
    fn from_create_dto(dto: CreateAttendanceCorrectionDto) -> backbone_core::ServiceResult<Self> {
        Ok(AttendanceCorrection::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateAttendanceCorrectionDto> for AttendanceCorrection {
    fn apply_update(mut self, dto: UpdateAttendanceCorrectionDto) -> backbone_core::ServiceResult<Self> {
        self.session_id = dto.session_id;
        self.employee_id = dto.employee_id;
        self.check_in = dto.check_in;
        self.check_out = dto.check_out;
        self.reason = dto.reason;
        self.status = dto.status;
        self.approval_request_id = dto.approval_request_id;
        self.submitted_at = dto.submitted_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to AttendanceCorrection here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

