//! Attendance DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate, NaiveTime};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Attendance;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Attendance
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateAttendanceDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub date: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub schedule: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub clockin: Option<NaiveTime>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub clockout: Option<NaiveTime>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "time_debt")]
    pub time_debt: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeoff: Option<serde_json::Value>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Attendance
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateAttendanceDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub date: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub schedule: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub clockin: Option<NaiveTime>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub clockout: Option<NaiveTime>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "time_debt")]
    pub time_debt: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timeoff: Option<serde_json::Value>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Attendance
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchAttendanceDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub schedule: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub clockin: Option<NaiveTime>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub clockout: Option<NaiveTime>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "time_debt")]
    pub time_debt: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timeoff: Option<serde_json::Value>,
}

impl PatchAttendanceDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.date.is_some() || self.schedule.is_some() || self.clockin.is_some() || self.clockout.is_some() || self.time_debt.is_some() || self.timeoff.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Attendance entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AttendanceResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub date: NaiveDate,
    pub schedule: Option<serde_json::Value>,
    pub clockin: Option<NaiveTime>,
    pub clockout: Option<NaiveTime>,
    pub time_debt: Option<serde_json::Value>,
    pub timeoff: Option<serde_json::Value>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Attendance entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AttendanceListResponseDto {
    /// List of items
    pub items: Vec<AttendanceResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl AttendanceListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<AttendanceResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AttendanceSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub date: NaiveDate,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Attendance> for AttendanceResponseDto {
    fn from(entity: Attendance) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            date: entity.date,
            schedule: entity.schedule,
            clockin: entity.clockin,
            clockout: entity.clockout,
            time_debt: entity.time_debt,
            timeoff: entity.timeoff,
            metadata: entity.metadata,
        }
    }
}

impl From<Attendance> for AttendanceSummaryDto {
    fn from(entity: Attendance) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            date: entity.date,
            created_at,
        }
    }
}

impl From<CreateAttendanceDto> for Attendance {
    fn from(dto: CreateAttendanceDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            employee_id: dto.employee_id,
            date: dto.date,
            schedule: dto.schedule,
            clockin: dto.clockin,
            clockout: dto.clockout,
            time_debt: dto.time_debt,
            timeoff: dto.timeoff,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Attendance> for AttendanceResponseDto {
    fn from(entity: &Attendance) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            employee_id: entity.employee_id.clone(),
            date: entity.date.clone(),
            schedule: entity.schedule.clone(),
            clockin: entity.clockin.clone(),
            clockout: entity.clockout.clone(),
            time_debt: entity.time_debt.clone(),
            timeoff: entity.timeoff.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateAttendanceDto> for Attendance {
    fn from_create_dto(dto: CreateAttendanceDto) -> backbone_core::ServiceResult<Self> {
        Ok(Attendance::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateAttendanceDto> for Attendance {
    fn apply_update(mut self, dto: UpdateAttendanceDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.employee_id = dto.employee_id;
        self.date = dto.date;
        self.schedule = dto.schedule;
        self.clockin = dto.clockin;
        self.clockout = dto.clockout;
        self.time_debt = dto.time_debt;
        self.timeoff = dto.timeoff;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Attendance here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

