//! KioskPin DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::KioskPin;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new KioskPin
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateKioskPinDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "badge_code")]
    pub badge_code: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "pin_hash")]
    pub pin_hash: String,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "failed_attempts")]
    pub failed_attempts: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "locked_until")]
    pub locked_until: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_attempt_at")]
    pub last_attempt_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "expires_at")]
    pub expires_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a KioskPin
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateKioskPinDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "badge_code")]
    pub badge_code: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "pin_hash")]
    pub pin_hash: String,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "failed_attempts")]
    pub failed_attempts: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "locked_until")]
    pub locked_until: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "last_attempt_at")]
    pub last_attempt_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "expires_at")]
    pub expires_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a KioskPin
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchKioskPinDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "badge_code")]
    pub badge_code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "pin_hash")]
    pub pin_hash: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "failed_attempts")]
    pub failed_attempts: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "locked_until")]
    pub locked_until: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "last_attempt_at")]
    pub last_attempt_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "expires_at")]
    pub expires_at: Option<DateTime<Utc>>,
}

impl PatchKioskPinDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.employee_id.is_some() || self.badge_code.is_some() || self.pin_hash.is_some() || self.failed_attempts.is_some() || self.locked_until.is_some() || self.last_attempt_at.is_some() || self.expires_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for KioskPin entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct KioskPinResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub badge_code: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub pin_hash: String,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub failed_attempts: i32,
    pub locked_until: Option<DateTime<Utc>>,
    pub last_attempt_at: Option<DateTime<Utc>>,
    pub expires_at: Option<DateTime<Utc>>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for KioskPin entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct KioskPinListResponseDto {
    /// List of items
    pub items: Vec<KioskPinResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl KioskPinListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<KioskPinResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct KioskPinSummaryDto {
    pub id: Uuid,
    pub employee_id: Uuid,
    pub badge_code: String,
    pub pin_hash: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<KioskPin> for KioskPinResponseDto {
    fn from(entity: KioskPin) -> Self {
        Self {
            id: entity.id,
            employee_id: entity.employee_id,
            badge_code: entity.badge_code,
            pin_hash: entity.pin_hash,
            failed_attempts: entity.failed_attempts,
            locked_until: entity.locked_until,
            last_attempt_at: entity.last_attempt_at,
            expires_at: entity.expires_at,
            metadata: entity.metadata,
        }
    }
}

impl From<KioskPin> for KioskPinSummaryDto {
    fn from(entity: KioskPin) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            employee_id: entity.employee_id,
            badge_code: entity.badge_code,
            pin_hash: entity.pin_hash,
            created_at,
        }
    }
}

impl From<CreateKioskPinDto> for KioskPin {
    fn from(dto: CreateKioskPinDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            employee_id: dto.employee_id,
            badge_code: dto.badge_code,
            pin_hash: dto.pin_hash,
            failed_attempts: dto.failed_attempts,
            locked_until: dto.locked_until,
            last_attempt_at: dto.last_attempt_at,
            expires_at: dto.expires_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&KioskPin> for KioskPinResponseDto {
    fn from(entity: &KioskPin) -> Self {
        Self {
            id: entity.id.clone(),
            employee_id: entity.employee_id.clone(),
            badge_code: entity.badge_code.clone(),
            pin_hash: entity.pin_hash.clone(),
            failed_attempts: entity.failed_attempts.clone(),
            locked_until: entity.locked_until.clone(),
            last_attempt_at: entity.last_attempt_at.clone(),
            expires_at: entity.expires_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateKioskPinDto> for KioskPin {
    fn from_create_dto(dto: CreateKioskPinDto) -> backbone_core::ServiceResult<Self> {
        Ok(KioskPin::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateKioskPinDto> for KioskPin {
    fn apply_update(mut self, dto: UpdateKioskPinDto) -> backbone_core::ServiceResult<Self> {
        self.employee_id = dto.employee_id;
        self.badge_code = dto.badge_code;
        self.pin_hash = dto.pin_hash;
        self.failed_attempts = dto.failed_attempts;
        self.locked_until = dto.locked_until;
        self.last_attempt_at = dto.last_attempt_at;
        self.expires_at = dto.expires_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to KioskPin here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
