//! OvertimeRequest DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::OvertimeRequest;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::OvertimeRequestStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new OvertimeRequest
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateOvertimeRequestDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub date: NaiveDate,
    #[serde(alias = "hours_planned")]
    pub hours_planned: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub reason: String,
    pub status: OvertimeRequestStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "approval_request_id")]
    pub approval_request_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "decided_at")]
    pub decided_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a OvertimeRequest
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateOvertimeRequestDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub date: NaiveDate,
    #[serde(alias = "hours_planned")]
    pub hours_planned: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub reason: String,
    pub status: OvertimeRequestStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "approval_request_id")]
    pub approval_request_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "decided_at")]
    pub decided_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a OvertimeRequest
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchOvertimeRequestDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "hours_planned")]
    pub hours_planned: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<OvertimeRequestStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "approval_request_id")]
    pub approval_request_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "decided_at")]
    pub decided_at: Option<DateTime<Utc>>,
}

impl PatchOvertimeRequestDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.employee_id.is_some() || self.date.is_some() || self.hours_planned.is_some() || self.reason.is_some() || self.status.is_some() || self.approval_request_id.is_some() || self.decided_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for OvertimeRequest entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OvertimeRequestResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub date: NaiveDate,
    pub hours_planned: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub reason: String,
    pub status: OvertimeRequestStatus,
    pub approval_request_id: Option<Uuid>,
    pub decided_at: Option<DateTime<Utc>>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for OvertimeRequest entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OvertimeRequestListResponseDto {
    /// List of items
    pub items: Vec<OvertimeRequestResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl OvertimeRequestListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<OvertimeRequestResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OvertimeRequestSummaryDto {
    pub id: Uuid,
    pub employee_id: Uuid,
    pub date: NaiveDate,
    pub hours_planned: Decimal,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<OvertimeRequest> for OvertimeRequestResponseDto {
    fn from(entity: OvertimeRequest) -> Self {
        Self {
            id: entity.id,
            employee_id: entity.employee_id,
            date: entity.date,
            hours_planned: entity.hours_planned,
            reason: entity.reason,
            status: entity.status,
            approval_request_id: entity.approval_request_id,
            decided_at: entity.decided_at,
            metadata: entity.metadata,
        }
    }
}

impl From<OvertimeRequest> for OvertimeRequestSummaryDto {
    fn from(entity: OvertimeRequest) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            employee_id: entity.employee_id,
            date: entity.date,
            hours_planned: entity.hours_planned,
            created_at,
        }
    }
}

impl From<CreateOvertimeRequestDto> for OvertimeRequest {
    fn from(dto: CreateOvertimeRequestDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            employee_id: dto.employee_id,
            date: dto.date,
            hours_planned: dto.hours_planned,
            reason: dto.reason,
            status: dto.status,
            approval_request_id: dto.approval_request_id,
            decided_at: dto.decided_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&OvertimeRequest> for OvertimeRequestResponseDto {
    fn from(entity: &OvertimeRequest) -> Self {
        Self {
            id: entity.id.clone(),
            employee_id: entity.employee_id.clone(),
            date: entity.date.clone(),
            hours_planned: entity.hours_planned.clone(),
            reason: entity.reason.clone(),
            status: entity.status.clone(),
            approval_request_id: entity.approval_request_id.clone(),
            decided_at: entity.decided_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateOvertimeRequestDto> for OvertimeRequest {
    fn from_create_dto(dto: CreateOvertimeRequestDto) -> backbone_core::ServiceResult<Self> {
        Ok(OvertimeRequest::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateOvertimeRequestDto> for OvertimeRequest {
    fn apply_update(mut self, dto: UpdateOvertimeRequestDto) -> backbone_core::ServiceResult<Self> {
        self.employee_id = dto.employee_id;
        self.date = dto.date;
        self.hours_planned = dto.hours_planned;
        self.reason = dto.reason;
        self.status = dto.status;
        self.approval_request_id = dto.approval_request_id;
        self.decided_at = dto.decided_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to OvertimeRequest here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
