//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod attendance_specification;
pub mod attendance_clock_specification;
pub mod attendance_correction_specification;
pub mod attendance_session_specification;
pub mod kiosk_pin_specification;
pub mod overtime_request_specification;
pub mod roster_entry_specification;
pub mod shift_specification;

// <<< CUSTOM
// END CUSTOM
