//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod attendance_domain_policy;
pub mod attendance_clock_domain_policy;

pub use attendance_domain_policy::AttendanceDomainPolicy;
pub use attendance_clock_domain_policy::AttendanceClockDomainPolicy;

// <<< CUSTOM
// END CUSTOM
