//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod attendance_domain_policy;
pub mod attendance_clock_domain_policy;
pub mod attendance_session_domain_policy;
pub mod kiosk_pin_domain_policy;

pub use attendance_domain_policy::AttendanceDomainPolicy;
pub use attendance_clock_domain_policy::AttendanceClockDomainPolicy;
pub use attendance_session_domain_policy::AttendanceSessionDomainPolicy;
pub use kiosk_pin_domain_policy::KioskPinDomainPolicy;

// <<< CUSTOM
// END CUSTOM
