//! Application service for AttendanceSession entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `attendance_session_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateAttendanceSessionDto, UpdateAttendanceSessionDto};
use crate::domain::entity::AttendanceSession;
use crate::infrastructure::persistence::AttendanceSessionRepository;

/// Application service for AttendanceSession entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `attendance_session_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct AttendanceSessionServiceCustom {
///     inner: Arc<AttendanceSessionService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type AttendanceSessionService = GenericCrudService<
    AttendanceSession,
    CreateAttendanceSessionDto,
    UpdateAttendanceSessionDto,
    AttendanceSessionRepository,
>;

// <<< CUSTOM
// END CUSTOM
