//! Application service for AttendanceClock entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `attendance_clock_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateAttendanceClockDto, UpdateAttendanceClockDto};
use crate::domain::entity::AttendanceClock;
use crate::infrastructure::persistence::AttendanceClockRepository;

/// Application service for AttendanceClock entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `attendance_clock_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct AttendanceClockServiceCustom {
///     inner: Arc<AttendanceClockService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type AttendanceClockService = GenericCrudService<
    AttendanceClock,
    CreateAttendanceClockDto,
    UpdateAttendanceClockDto,
    AttendanceClockRepository,
>;

// <<< CUSTOM
// END CUSTOM
