//! Application service for AttendanceCorrection entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `attendance_correction_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateAttendanceCorrectionDto, UpdateAttendanceCorrectionDto};
use crate::domain::entity::AttendanceCorrection;
use crate::infrastructure::persistence::AttendanceCorrectionRepository;

/// Application service for AttendanceCorrection entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `attendance_correction_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct AttendanceCorrectionServiceCustom {
///     inner: Arc<AttendanceCorrectionService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type AttendanceCorrectionService = GenericCrudService<
    AttendanceCorrection,
    CreateAttendanceCorrectionDto,
    UpdateAttendanceCorrectionDto,
    AttendanceCorrectionRepository,
>;

// <<< CUSTOM
// END CUSTOM
