//! Application service for KioskPin entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `kiosk_pin_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateKioskPinDto, UpdateKioskPinDto};
use crate::domain::entity::KioskPin;
use crate::infrastructure::persistence::KioskPinRepository;

/// Application service for KioskPin entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `kiosk_pin_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct KioskPinServiceCustom {
///     inner: Arc<KioskPinService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type KioskPinService = GenericCrudService<
    KioskPin,
    CreateKioskPinDto,
    UpdateKioskPinDto,
    KioskPinRepository,
>;

// <<< CUSTOM
// END CUSTOM
