//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod attendance_service;
pub mod attendance_clock_service;
pub mod attendance_session_service;
pub mod kiosk_pin_service;
pub mod overtime_request_service;
pub mod roster_entry_service;
pub mod shift_service;

// <<< CUSTOM
pub mod overtime_approvals_port;
pub mod overtime_request_lifecycle;
// Hand-written `AttendanceQueryService` impl (user-owned file). Standard lookups delegate to the
// GenericCrudService aliases above; the `present_days` read-port delegates to the repo's SQL.
pub mod attendance_query_service;
// The validated write path (punch in/out, kiosk Tier B PIN, session corrections) — H-3.
pub mod attendance_write_service;
// END CUSTOM

pub use attendance_service::AttendanceService;
pub use attendance_clock_service::AttendanceClockService;
pub use attendance_session_service::AttendanceSessionService;
pub use kiosk_pin_service::KioskPinService;
pub use overtime_request_service::OvertimeRequestService;
pub use roster_entry_service::RosterEntryService;
pub use shift_service::ShiftService;
// <<< CUSTOM
pub use attendance_write_service::{
    lockout_until, pin_is_wellformed, validate_punch_time, AttendanceWriteError,
    AttendanceWriteService, PunchOutcome, PIN_ATTEMPT_SPACING, PIN_LOCK_BASE, PIN_LOCK_MAX,
    PIN_MAX_ATTEMPTS, PUNCH_CLOCK_SKEW,
};
// END CUSTOM
