//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod attendance_service;
pub mod attendance_clock_service;

// <<< CUSTOM
// Hand-written `AttendanceQueryService` impl (user-owned file). Standard lookups delegate to the
// GenericCrudService aliases above; the `present_days` read-port delegates to the repo's SQL.
pub mod attendance_query_service;
// END CUSTOM

pub use attendance_service::AttendanceService;
pub use attendance_clock_service::AttendanceClockService;
// <<< CUSTOM
// END CUSTOM
