//! Application service for OvertimeRequest entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `overtime_request_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateOvertimeRequestDto, UpdateOvertimeRequestDto};
use crate::domain::entity::OvertimeRequest;
use crate::infrastructure::persistence::OvertimeRequestRepository;

/// Application service for OvertimeRequest entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `overtime_request_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct OvertimeRequestServiceCustom {
///     inner: Arc<OvertimeRequestService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type OvertimeRequestService = GenericCrudService<
    OvertimeRequest,
    CreateOvertimeRequestDto,
    UpdateOvertimeRequestDto,
    OvertimeRequestRepository,
>;

// <<< CUSTOM
// END CUSTOM
