//! Application service for RosterEntry entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `roster_entry_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateRosterEntryDto, UpdateRosterEntryDto};
use crate::domain::entity::RosterEntry;
use crate::infrastructure::persistence::RosterEntryRepository;

/// Application service for RosterEntry entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `roster_entry_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct RosterEntryServiceCustom {
///     inner: Arc<RosterEntryService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type RosterEntryService = GenericCrudService<
    RosterEntry,
    CreateRosterEntryDto,
    UpdateRosterEntryDto,
    RosterEntryRepository,
>;

// <<< CUSTOM
// END CUSTOM
