//! Application service for Shift entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `shift_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateShiftDto, UpdateShiftDto};
use crate::domain::entity::Shift;
use crate::infrastructure::persistence::ShiftRepository;

/// Application service for Shift entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `shift_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ShiftServiceCustom {
///     inner: Arc<ShiftService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ShiftService = GenericCrudService<
    Shift,
    CreateShiftDto,
    UpdateShiftDto,
    ShiftRepository,
>;

// <<< CUSTOM
// END CUSTOM
