-- AttendanceSession Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the attendance.attendance_sessions table.
-- Customize this file to add your initial data.

-- INSERT INTO attendance.attendance_sessions (
--     id,
--     company_id,
--     employee_id,
--     date,
--     check_in,
--     check_out,
--     source,
--     correction_reason,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO attendance.attendance_sessions (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

