-- AttendanceCorrection Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the attendance.attendance_corrections table.
-- Customize this file to add your initial data.

-- INSERT INTO attendance.attendance_corrections (
--     id,
--     session_id,
--     employee_id,
--     check_in,
--     check_out,
--     reason,
--     status,
--     approval_request_id,
--     submitted_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO attendance.attendance_corrections (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

