-- AttendanceClock Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the attendance.attendance_clocks table.
-- Customize this file to add your initial data.

-- INSERT INTO attendance.attendance_clocks (
--     id,
--     company_id,
--     attendance_id,
--     employee_id,
--     date,
--     clock,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO attendance.attendance_clocks (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

