-- Attendance Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the attendance.attendances table.
-- Customize this file to add your initial data.

-- INSERT INTO attendance.attendances (
--     id,
--     company_id,
--     employee_id,
--     date,
--     schedule,
--     clockin,
--     clockout,
--     time_debt,
--     timeoff,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO attendance.attendances (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

