-- RosterEntry Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the attendance.roster_entries table.
-- Customize this file to add your initial data.

-- INSERT INTO attendance.roster_entries (
--     id,
--     employee_id,
--     date,
--     shift_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO attendance.roster_entries (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

