-- Shift Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the attendance.shifts table.
-- Customize this file to add your initial data.

-- INSERT INTO attendance.shifts (
--     id,
--     name,
--     code,
--     start_time,
--     end_time,
--     break_minutes,
--     is_active,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO attendance.shifts (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

