-- Migration: Create kiosk_pins table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS attendance;

CREATE TABLE IF NOT EXISTS attendance.kiosk_pins (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    badge_code TEXT NOT NULL,
    pin_hash TEXT NOT NULL,
    failed_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMPTZ,
    last_attempt_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_kiosk_pins_company_id_badge_code ON attendance.kiosk_pins (company_id, badge_code) WHERE (metadata->>'deleted_at') IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_kiosk_pins_company_id_employee_id ON attendance.kiosk_pins (company_id, employee_id) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_kiosk_pins_metadata_gin ON attendance.kiosk_pins USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_kiosk_pins_metadata_deleted_at ON attendance.kiosk_pins ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_kiosk_pins_metadata_created_at ON attendance.kiosk_pins ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_kiosk_pins_metadata_updated_at ON attendance.kiosk_pins ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION attendance.kiosk_pins_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS kiosk_pins_insert_audit ON attendance.kiosk_pins;
CREATE TRIGGER kiosk_pins_insert_audit BEFORE INSERT ON attendance.kiosk_pins
    FOR EACH ROW EXECUTE FUNCTION attendance.kiosk_pins_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS kiosk_pins_update_audit ON attendance.kiosk_pins;
CREATE TRIGGER kiosk_pins_update_audit BEFORE UPDATE ON attendance.kiosk_pins
    FOR EACH ROW EXECUTE FUNCTION attendance.kiosk_pins_audit_timestamp();
