-- Company RLS fence for attendance module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for attendance.attendances
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE attendance.attendances ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance.attendances FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS attendances_company_isolation ON attendance.attendances;
CREATE POLICY attendances_company_isolation ON attendance.attendances
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for attendance.attendance_clocks
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE attendance.attendance_clocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance.attendance_clocks FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS attendance_clocks_company_isolation ON attendance.attendance_clocks;
CREATE POLICY attendance_clocks_company_isolation ON attendance.attendance_clocks
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

