-- Migration: Create attendance_clocks table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS attendance;

CREATE TABLE IF NOT EXISTS attendance.attendance_clocks (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    attendance_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    date DATE NOT NULL,
    clock TIME NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_attendance_clocks_attendance_id ON attendance.attendance_clocks (attendance_id);

CREATE INDEX IF NOT EXISTS idx_attendance_clocks_employee_id_date ON attendance.attendance_clocks (employee_id, date);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_attendance_clocks_metadata_gin ON attendance.attendance_clocks USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_attendance_clocks_metadata_deleted_at ON attendance.attendance_clocks ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_attendance_clocks_metadata_created_at ON attendance.attendance_clocks ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_attendance_clocks_metadata_updated_at ON attendance.attendance_clocks ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION attendance.attendance_clocks_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS attendance_clocks_insert_audit ON attendance.attendance_clocks;
CREATE TRIGGER attendance_clocks_insert_audit BEFORE INSERT ON attendance.attendance_clocks
    FOR EACH ROW EXECUTE FUNCTION attendance.attendance_clocks_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS attendance_clocks_update_audit ON attendance.attendance_clocks;
CREATE TRIGGER attendance_clocks_update_audit BEFORE UPDATE ON attendance.attendance_clocks
    FOR EACH ROW EXECUTE FUNCTION attendance.attendance_clocks_audit_timestamp();
