-- Migration: Create overtime_requests table
-- Generated by metaphor-schema

-- Create overtime_request_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'overtime_request_status') THEN
        CREATE TYPE overtime_request_status AS ENUM ('pending', 'approved', 'rejected', 'cancelled');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS attendance;

CREATE TABLE IF NOT EXISTS attendance.overtime_requests (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    employee_id UUID NOT NULL,
    date DATE NOT NULL,
    hours_planned NUMERIC(5, 2) NOT NULL,
    reason TEXT NOT NULL,
    status overtime_request_status NOT NULL DEFAULT 'pending',
    approval_request_id UUID,
    decided_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_overtime_requests_employee_id_date ON attendance.overtime_requests (employee_id, date);

CREATE INDEX IF NOT EXISTS idx_overtime_requests_status ON attendance.overtime_requests (status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_overtime_requests_metadata_gin ON attendance.overtime_requests USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_overtime_requests_metadata_deleted_at ON attendance.overtime_requests ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_overtime_requests_metadata_created_at ON attendance.overtime_requests ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_overtime_requests_metadata_updated_at ON attendance.overtime_requests ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION attendance.overtime_requests_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS overtime_requests_insert_audit ON attendance.overtime_requests;
CREATE TRIGGER overtime_requests_insert_audit BEFORE INSERT ON attendance.overtime_requests
    FOR EACH ROW EXECUTE FUNCTION attendance.overtime_requests_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS overtime_requests_update_audit ON attendance.overtime_requests;
CREATE TRIGGER overtime_requests_update_audit BEFORE UPDATE ON attendance.overtime_requests
    FOR EACH ROW EXECUTE FUNCTION attendance.overtime_requests_audit_timestamp();
