-- Revert the ADR-0014 strict company fence for attendance module (Wave 1 P0 sweep).
-- Generated by metaphor-schema.
DROP POLICY IF EXISTS attendance_clocks_company_isolation ON attendance.attendance_clocks;
ALTER TABLE attendance.attendance_clocks NO FORCE ROW LEVEL SECURITY;
ALTER TABLE attendance.attendance_clocks DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS attendances_company_isolation ON attendance.attendances;
ALTER TABLE attendance.attendances NO FORCE ROW LEVEL SECURITY;
ALTER TABLE attendance.attendances DISABLE ROW LEVEL SECURITY;
