-- Company fence posture for attendance module (ADR-0014: strict)
-- Generated by metaphor-schema. Every entity here carries company_id and is fenced
-- strict: a session sees only rows whose company_id equals the request-scoped
-- company (`set_config('app.company_id', <uuid>, true)`); an unset var sees zero
-- rows (fail-closed). These tables shipped company_id without a policy since the
-- pre-ADR-0014 policy cleanup; this migration installs the declared fence
-- (Wave 1 P0 sweep, 2026-08-16). Requires the app to connect as a non-superuser
-- role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for attendance.attendance_clocks
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE attendance.attendance_clocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance.attendance_clocks FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS attendance_clocks_company_isolation ON attendance.attendance_clocks;
CREATE POLICY attendance_clocks_company_isolation ON attendance.attendance_clocks
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for attendance.attendances
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE attendance.attendances ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance.attendances FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS attendances_company_isolation ON attendance.attendances;
CREATE POLICY attendances_company_isolation ON attendance.attendances
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);
