-- Migration: Create shifts table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS attendance;

CREATE TABLE IF NOT EXISTS attendance.shifts (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    code TEXT NOT NULL,
    start_time TIME,
    end_time TIME,
    break_minutes INTEGER,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_shifts_code ON attendance.shifts (code);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_shifts_metadata_gin ON attendance.shifts USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_shifts_metadata_deleted_at ON attendance.shifts ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_shifts_metadata_created_at ON attendance.shifts ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_shifts_metadata_updated_at ON attendance.shifts ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION attendance.shifts_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS shifts_insert_audit ON attendance.shifts;
CREATE TRIGGER shifts_insert_audit BEFORE INSERT ON attendance.shifts
    FOR EACH ROW EXECUTE FUNCTION attendance.shifts_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS shifts_update_audit ON attendance.shifts;
CREATE TRIGGER shifts_update_audit BEFORE UPDATE ON attendance.shifts
    FOR EACH ROW EXECUTE FUNCTION attendance.shifts_audit_timestamp();
