-- Migration: Create roster_entries table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS attendance;

CREATE TABLE IF NOT EXISTS attendance.roster_entries (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    employee_id UUID NOT NULL,
    date DATE NOT NULL,
    shift_id UUID,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_roster_entries_employee_id_date ON attendance.roster_entries (employee_id, date);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_roster_entries_metadata_gin ON attendance.roster_entries USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_roster_entries_metadata_deleted_at ON attendance.roster_entries ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_roster_entries_metadata_created_at ON attendance.roster_entries ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_roster_entries_metadata_updated_at ON attendance.roster_entries ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION attendance.roster_entries_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS roster_entries_insert_audit ON attendance.roster_entries;
CREATE TRIGGER roster_entries_insert_audit BEFORE INSERT ON attendance.roster_entries
    FOR EACH ROW EXECUTE FUNCTION attendance.roster_entries_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS roster_entries_update_audit ON attendance.roster_entries;
CREATE TRIGGER roster_entries_update_audit BEFORE UPDATE ON attendance.roster_entries
    FOR EACH ROW EXECUTE FUNCTION attendance.roster_entries_audit_timestamp();
