-- Enum types for attendance module
-- Generated by metaphor-schema

-- Create punch_direction enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'punch_direction') THEN
        CREATE TYPE punch_direction AS ENUM ('in', 'out');
    END IF;
END
$$;

-- Create punch_source enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'punch_source') THEN
        CREATE TYPE punch_source AS ENUM ('kiosk', 'self_service', 'admin');
    END IF;
END
$$;

