-- Migration: Create attendance_corrections table
-- Generated by metaphor-schema

-- Create correction_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'correction_status') THEN
        CREATE TYPE correction_status AS ENUM ('pending', 'applied', 'rejected', 'cancelled');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS attendance;

CREATE TABLE IF NOT EXISTS attendance.attendance_corrections (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    session_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    check_in TIMESTAMPTZ NOT NULL,
    check_out TIMESTAMPTZ,
    reason TEXT NOT NULL,
    status correction_status NOT NULL DEFAULT 'pending',
    approval_request_id UUID,
    submitted_at TIMESTAMPTZ NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_attendance_corrections_session_id ON attendance.attendance_corrections (session_id);

CREATE INDEX IF NOT EXISTS idx_attendance_corrections_employee_id ON attendance.attendance_corrections (employee_id);

CREATE INDEX IF NOT EXISTS idx_attendance_corrections_status ON attendance.attendance_corrections (status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_attendance_corrections_metadata_gin ON attendance.attendance_corrections USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_attendance_corrections_metadata_deleted_at ON attendance.attendance_corrections ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_attendance_corrections_metadata_created_at ON attendance.attendance_corrections ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_attendance_corrections_metadata_updated_at ON attendance.attendance_corrections ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION attendance.attendance_corrections_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS attendance_corrections_insert_audit ON attendance.attendance_corrections;
CREATE TRIGGER attendance_corrections_insert_audit BEFORE INSERT ON attendance.attendance_corrections
    FOR EACH ROW EXECUTE FUNCTION attendance.attendance_corrections_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS attendance_corrections_update_audit ON attendance.attendance_corrections;
CREATE TRIGGER attendance_corrections_update_audit BEFORE UPDATE ON attendance.attendance_corrections
    FOR EACH ROW EXECUTE FUNCTION attendance.attendance_corrections_audit_timestamp();
