-- Migration: Create attendance_sessions table
-- Generated by metaphor-schema

-- Create punch_source enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'punch_source') THEN
        CREATE TYPE punch_source AS ENUM ('kiosk', 'self_service', 'admin');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS attendance;

CREATE TABLE IF NOT EXISTS attendance.attendance_sessions (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    date DATE NOT NULL,
    check_in TIMESTAMPTZ NOT NULL,
    check_out TIMESTAMPTZ,
    source punch_source NOT NULL DEFAULT 'kiosk',
    correction_reason TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_attendance_sessions_company_id_employee_id ON attendance.attendance_sessions (company_id, employee_id);

CREATE INDEX IF NOT EXISTS idx_attendance_sessions_company_id_date ON attendance.attendance_sessions (company_id, date);

CREATE INDEX IF NOT EXISTS idx_attendance_sessions_company_id_employee_id ON attendance.attendance_sessions (company_id, employee_id) WHERE check_out IS NULL AND (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_attendance_sessions_metadata_gin ON attendance.attendance_sessions USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_attendance_sessions_metadata_deleted_at ON attendance.attendance_sessions ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_attendance_sessions_metadata_created_at ON attendance.attendance_sessions ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_attendance_sessions_metadata_updated_at ON attendance.attendance_sessions ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION attendance.attendance_sessions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS attendance_sessions_insert_audit ON attendance.attendance_sessions;
CREATE TRIGGER attendance_sessions_insert_audit BEFORE INSERT ON attendance.attendance_sessions
    FOR EACH ROW EXECUTE FUNCTION attendance.attendance_sessions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS attendance_sessions_update_audit ON attendance.attendance_sessions;
CREATE TRIGGER attendance_sessions_update_audit BEFORE UPDATE ON attendance.attendance_sessions
    FOR EACH ROW EXECUTE FUNCTION attendance.attendance_sessions_audit_timestamp();
