-- Audit Triggers Migration for attendance module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: Attendance (attendance.attendances)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION attendance.attendances_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS attendances_insert_audit ON attendance.attendances;
CREATE TRIGGER attendances_insert_audit BEFORE INSERT ON attendance.attendances
    FOR EACH ROW EXECUTE FUNCTION attendance.attendances_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS attendances_update_audit ON attendance.attendances;
CREATE TRIGGER attendances_update_audit BEFORE UPDATE ON attendance.attendances
    FOR EACH ROW EXECUTE FUNCTION attendance.attendances_audit_timestamp();

-- ==============================================================================
-- Table: AttendanceClock (attendance.attendance_clocks)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION attendance.attendance_clocks_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS attendance_clocks_insert_audit ON attendance.attendance_clocks;
CREATE TRIGGER attendance_clocks_insert_audit BEFORE INSERT ON attendance.attendance_clocks
    FOR EACH ROW EXECUTE FUNCTION attendance.attendance_clocks_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS attendance_clocks_update_audit ON attendance.attendance_clocks;
CREATE TRIGGER attendance_clocks_update_audit BEFORE UPDATE ON attendance.attendance_clocks
    FOR EACH ROW EXECUTE FUNCTION attendance.attendance_clocks_audit_timestamp();

