//! Event handler trait for AttendanceCorrection events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::AttendanceCorrectionEvent;

/// Event handler for AttendanceCorrection events.
/// Implement this trait to react to AttendanceCorrection lifecycle events.
pub trait AttendanceCorrectionEventHandler: EventHandler<AttendanceCorrectionEvent> {}
