//! Domain events for AttendanceSession entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::AttendanceSession;

/// Domain events for AttendanceSession — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<AttendanceSession>)` variant.
pub type AttendanceSessionEvent = CrudEvent<AttendanceSession>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for AttendanceSession events.
pub type AttendanceSessionEventPublisher = Arc<dyn CrudEventPublisher<AttendanceSession> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopAttendanceSessionEventPublisher = NoOpCrudEventPublisher<AttendanceSession>;
