//! Domain events for AttendanceCorrection entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::AttendanceCorrection;

/// Domain events for AttendanceCorrection — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<AttendanceCorrection>)` variant.
pub type AttendanceCorrectionEvent = CrudEvent<AttendanceCorrection>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for AttendanceCorrection events.
pub type AttendanceCorrectionEventPublisher = Arc<dyn CrudEventPublisher<AttendanceCorrection> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopAttendanceCorrectionEventPublisher = NoOpCrudEventPublisher<AttendanceCorrection>;
