//! Domain events for AttendanceClock entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::AttendanceClock;

/// Domain events for AttendanceClock — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<AttendanceClock>)` variant.
pub type AttendanceClockEvent = CrudEvent<AttendanceClock>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for AttendanceClock events.
pub type AttendanceClockEventPublisher = Arc<dyn CrudEventPublisher<AttendanceClock> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopAttendanceClockEventPublisher = NoOpCrudEventPublisher<AttendanceClock>;
