//! Event handler trait for AttendanceClock events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::AttendanceClockEvent;

/// Event handler for AttendanceClock events.
/// Implement this trait to react to AttendanceClock lifecycle events.
pub trait AttendanceClockEventHandler: EventHandler<AttendanceClockEvent> {}
