//! Event handler trait for AttendanceSession events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::AttendanceSessionEvent;

/// Event handler for AttendanceSession events.
/// Implement this trait to react to AttendanceSession lifecycle events.
pub trait AttendanceSessionEventHandler: EventHandler<AttendanceSessionEvent> {}
