//! Domain events for KioskPin entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::KioskPin;

/// Domain events for KioskPin — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<KioskPin>)` variant.
pub type KioskPinEvent = CrudEvent<KioskPin>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for KioskPin events.
pub type KioskPinEventPublisher = Arc<dyn CrudEventPublisher<KioskPin> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopKioskPinEventPublisher = NoOpCrudEventPublisher<KioskPin>;
