//! Event handler trait for KioskPin events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::KioskPinEvent;

/// Event handler for KioskPin events.
/// Implement this trait to react to KioskPin lifecycle events.
pub trait KioskPinEventHandler: EventHandler<KioskPinEvent> {}
