//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod attendance_events;
pub mod attendance_event_handlers;
pub mod attendance_clock_events;
pub mod attendance_clock_event_handlers;

pub use attendance_events::{AttendanceEvent, AttendanceEventPublisher, NoopAttendanceEventPublisher};
pub use attendance_event_handlers::AttendanceEventHandler;
pub use attendance_clock_events::{AttendanceClockEvent, AttendanceClockEventPublisher, NoopAttendanceClockEventPublisher};
pub use attendance_clock_event_handlers::AttendanceClockEventHandler;

// <<< CUSTOM
// END CUSTOM
