//! Event handler trait for OvertimeRequest events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::OvertimeRequestEvent;

/// Event handler for OvertimeRequest events.
/// Implement this trait to react to OvertimeRequest lifecycle events.
pub trait OvertimeRequestEventHandler: EventHandler<OvertimeRequestEvent> {}
