//! Event handler trait for RosterEntry events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::RosterEntryEvent;

/// Event handler for RosterEntry events.
/// Implement this trait to react to RosterEntry lifecycle events.
pub trait RosterEntryEventHandler: EventHandler<RosterEntryEvent> {}
