//! Domain events for RosterEntry entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::RosterEntry;

/// Domain events for RosterEntry — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<RosterEntry>)` variant.
pub type RosterEntryEvent = CrudEvent<RosterEntry>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for RosterEntry events.
pub type RosterEntryEventPublisher = Arc<dyn CrudEventPublisher<RosterEntry> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopRosterEntryEventPublisher = NoOpCrudEventPublisher<RosterEntry>;
