//! Domain events for Shift entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Shift;

/// Domain events for Shift — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Shift>)` variant.
pub type ShiftEvent = CrudEvent<Shift>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Shift events.
pub type ShiftEventPublisher = Arc<dyn CrudEventPublisher<Shift> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopShiftEventPublisher = NoOpCrudEventPublisher<Shift>;
