//! Event handler trait for Shift events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ShiftEvent;

/// Event handler for Shift events.
/// Implement this trait to react to Shift lifecycle events.
pub trait ShiftEventHandler: EventHandler<ShiftEvent> {}
