//! AttendanceClock seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial AttendanceClock data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// ATTENDANCECLOCK SEEDER
// ============================================================================

/// Seeder for attendance_clock
pub struct SeedAttendanceClockSeeder;

impl SeedAttendanceClockSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedAttendanceClockSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedAttendanceClockSeeder {
    fn name(&self) -> &'static str {
        "SeedAttendanceClockSeeder"
    }

    fn order(&self) -> i32 {
        2
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if attendance.attendance_clocks table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM attendance.attendance_clocks")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/attendance_clock_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM attendance.attendance_clocks")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

