//! KioskPin seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial KioskPin data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// KIOSKPIN SEEDER
// ============================================================================

/// Seeder for kiosk_pin
pub struct SeedKioskPinSeeder;

impl SeedKioskPinSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedKioskPinSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedKioskPinSeeder {
    fn name(&self) -> &'static str {
        "SeedKioskPinSeeder"
    }

    fn order(&self) -> i32 {
        5
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if attendance.kiosk_pins table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM attendance.kiosk_pins")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/kiosk_pin_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM attendance.kiosk_pins")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
