//! Database seeders for the attendance module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides seed data for initial database setup.
//! Seeders can be run via the seeder binary or CLI.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

mod attendance_seeder;
mod attendance_clock_seeder;
mod attendance_correction_seeder;
mod attendance_session_seeder;
mod kiosk_pin_seeder;
mod overtime_request_seeder;
mod roster_entry_seeder;
mod shift_seeder;

pub use attendance_seeder::SeedAttendanceSeeder;
pub use attendance_clock_seeder::SeedAttendanceClockSeeder;
pub use attendance_correction_seeder::SeedAttendanceCorrectionSeeder;
pub use attendance_session_seeder::SeedAttendanceSessionSeeder;
pub use kiosk_pin_seeder::SeedKioskPinSeeder;
pub use overtime_request_seeder::SeedOvertimeRequestSeeder;
pub use roster_entry_seeder::SeedRosterEntrySeeder;
pub use shift_seeder::SeedShiftSeeder;

// ============================================================================
// SEEDER TRAIT
// ============================================================================

/// Trait for database seeders
#[async_trait]
pub trait Seeder {
    /// Get the name of this seeder
    fn name(&self) -> &'static str;

    /// Get the order in which this seeder should run
    fn order(&self) -> i32;

    /// Check if this seeder should run (e.g., check if data already exists)
    async fn should_run(&self, pool: &PgPool) -> Result<bool>;

    /// Run the seeder
    async fn run(&self, pool: &PgPool) -> Result<()>;

    /// Rollback the seeder (optional)
    async fn rollback(&self, _pool: &PgPool) -> Result<()> {
        Ok(())
    }
}

// ============================================================================
// SEEDER TYPE
// ============================================================================

/// Type of seeder
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SeederType {
    /// Reference data (required for application to function)
    Reference,
    /// Initial production data
    Production,
    /// Development/testing data
    Development,
    /// Test data (for automated tests)
    Test,
}

// ============================================================================
// CUSTOM SEEDERS
// ============================================================================

// <<< CUSTOM SEEDERS START >>>
// Add custom seeders here
// <<< CUSTOM SEEDERS END >>>
