//! OvertimeRequest seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial OvertimeRequest data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// OVERTIMEREQUEST SEEDER
// ============================================================================

/// Seeder for overtime_request
pub struct SeedOvertimeRequestSeeder;

impl SeedOvertimeRequestSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedOvertimeRequestSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedOvertimeRequestSeeder {
    fn name(&self) -> &'static str {
        "SeedOvertimeRequestSeeder"
    }

    fn order(&self) -> i32 {
        5
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if attendance.overtime_requests table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM attendance.overtime_requests")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/overtime_request_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM attendance.overtime_requests")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
