//! RosterEntry seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial RosterEntry data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// ROSTERENTRY SEEDER
// ============================================================================

/// Seeder for roster_entry
pub struct SeedRosterEntrySeeder;

impl SeedRosterEntrySeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedRosterEntrySeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedRosterEntrySeeder {
    fn name(&self) -> &'static str {
        "SeedRosterEntrySeeder"
    }

    fn order(&self) -> i32 {
        7
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if attendance.roster_entries table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM attendance.roster_entries")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/roster_entry_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM attendance.roster_entries")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
