//! Repository trait for AttendanceCorrection aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the AttendanceCorrection aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{AttendanceCorrection, CorrectionStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AttendanceCorrectionPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl AttendanceCorrectionPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct AttendanceCorrectionPaginatedResult {
    pub data: Vec<AttendanceCorrection>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AttendanceCorrectionFilter {
    pub session_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub reason: Option<String>,
    pub status: Option<CorrectionStatus>,
    pub approval_request_id: Option<Uuid>,
}

impl AttendanceCorrectionFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.session_id.is_some() || self.employee_id.is_some() || self.reason.is_some() || self.status.is_some() || self.approval_request_id.is_some()
    }
}

/// Repository trait for AttendanceCorrection aggregate
///
/// This trait defines the persistence contract for AttendanceCorrection entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait AttendanceCorrectionRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new attendance_correction entity
    async fn save(&self, entity: &AttendanceCorrection) -> Result<AttendanceCorrection>;

    /// Find attendance_correction by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<AttendanceCorrection>>;

    /// Find all attendance_correction entities
    async fn find_all(&self) -> Result<Vec<AttendanceCorrection>>;

    /// Update attendance_correction by ID
    async fn update(&self, id: &str, entity: &AttendanceCorrection) -> Result<Option<AttendanceCorrection>>;

    /// Delete attendance_correction by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List attendance_correction with pagination
    async fn list(&self, params: AttendanceCorrectionPaginationParams) -> Result<AttendanceCorrectionPaginatedResult>;

    /// List attendance_correction with pagination and filters
    async fn list_with_filters(&self, params: AttendanceCorrectionPaginationParams, filters: AttendanceCorrectionFilter) -> Result<AttendanceCorrectionPaginatedResult>;

    /// Count all attendance_correction entities
    async fn count(&self) -> Result<u64>;

    /// Count attendance_correction entities matching filters
    async fn count_with_filters(&self, filters: AttendanceCorrectionFilter) -> Result<u64>;

    /// Check if attendance_correction exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete attendance_correction by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted attendance_correction by ID
    async fn restore(&self, id: &str) -> Result<Option<AttendanceCorrection>>;

    /// List soft-deleted attendance_correction entities
    async fn list_deleted(&self, params: AttendanceCorrectionPaginationParams) -> Result<AttendanceCorrectionPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save attendance_correction entities
    async fn bulk_save(&self, entities: &[AttendanceCorrection]) -> Result<Vec<AttendanceCorrection>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
