//! Repository trait for AttendanceSession aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the AttendanceSession aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{AttendanceSession, PunchSource};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AttendanceSessionPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl AttendanceSessionPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct AttendanceSessionPaginatedResult {
    pub data: Vec<AttendanceSession>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AttendanceSessionFilter {
    pub employee_id: Option<Uuid>,
    pub source: Option<PunchSource>,
    pub correction_reason: Option<String>,
}

impl AttendanceSessionFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.employee_id.is_some() || self.source.is_some() || self.correction_reason.is_some()
    }
}

/// Repository trait for AttendanceSession aggregate
///
/// This trait defines the persistence contract for AttendanceSession entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait AttendanceSessionRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new attendance_session entity
    async fn save(&self, entity: &AttendanceSession) -> Result<AttendanceSession>;

    /// Find attendance_session by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<AttendanceSession>>;

    /// Find all attendance_session entities
    async fn find_all(&self) -> Result<Vec<AttendanceSession>>;

    /// Update attendance_session by ID
    async fn update(&self, id: &str, entity: &AttendanceSession) -> Result<Option<AttendanceSession>>;

    /// Delete attendance_session by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List attendance_session with pagination
    async fn list(&self, params: AttendanceSessionPaginationParams) -> Result<AttendanceSessionPaginatedResult>;

    /// List attendance_session with pagination and filters
    async fn list_with_filters(&self, params: AttendanceSessionPaginationParams, filters: AttendanceSessionFilter) -> Result<AttendanceSessionPaginatedResult>;

    /// Count all attendance_session entities
    async fn count(&self) -> Result<u64>;

    /// Count attendance_session entities matching filters
    async fn count_with_filters(&self, filters: AttendanceSessionFilter) -> Result<u64>;

    /// Check if attendance_session exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete attendance_session by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted attendance_session by ID
    async fn restore(&self, id: &str) -> Result<Option<AttendanceSession>>;

    /// List soft-deleted attendance_session entities
    async fn list_deleted(&self, params: AttendanceSessionPaginationParams) -> Result<AttendanceSessionPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save attendance_session entities
    async fn bulk_save(&self, entities: &[AttendanceSession]) -> Result<Vec<AttendanceSession>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
