//! Repository trait for AttendanceClock aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the AttendanceClock aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{AttendanceClock, PunchDirection};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AttendanceClockPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl AttendanceClockPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct AttendanceClockPaginatedResult {
    pub data: Vec<AttendanceClock>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AttendanceClockFilter {
    pub session_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub direction: Option<PunchDirection>,
}

impl AttendanceClockFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.session_id.is_some() || self.employee_id.is_some() || self.direction.is_some()
    }
}

/// Repository trait for AttendanceClock aggregate
///
/// This trait defines the persistence contract for AttendanceClock entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait AttendanceClockRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new attendance_clock entity
    async fn save(&self, entity: &AttendanceClock) -> Result<AttendanceClock>;

    /// Find attendance_clock by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<AttendanceClock>>;

    /// Find all attendance_clock entities
    async fn find_all(&self) -> Result<Vec<AttendanceClock>>;

    /// Update attendance_clock by ID
    async fn update(&self, id: &str, entity: &AttendanceClock) -> Result<Option<AttendanceClock>>;

    /// Delete attendance_clock by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List attendance_clock with pagination
    async fn list(&self, params: AttendanceClockPaginationParams) -> Result<AttendanceClockPaginatedResult>;

    /// List attendance_clock with pagination and filters
    async fn list_with_filters(&self, params: AttendanceClockPaginationParams, filters: AttendanceClockFilter) -> Result<AttendanceClockPaginatedResult>;

    /// Count all attendance_clock entities
    async fn count(&self) -> Result<u64>;

    /// Count attendance_clock entities matching filters
    async fn count_with_filters(&self, filters: AttendanceClockFilter) -> Result<u64>;

    /// Check if attendance_clock exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete attendance_clock by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted attendance_clock by ID
    async fn restore(&self, id: &str) -> Result<Option<AttendanceClock>>;

    /// List soft-deleted attendance_clock entities
    async fn list_deleted(&self, params: AttendanceClockPaginationParams) -> Result<AttendanceClockPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save attendance_clock entities
    async fn bulk_save(&self, entities: &[AttendanceClock]) -> Result<Vec<AttendanceClock>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
