//! Repository trait for KioskPin aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the KioskPin aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::KioskPin;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct KioskPinPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl KioskPinPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct KioskPinPaginatedResult {
    pub data: Vec<KioskPin>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct KioskPinFilter {
    pub employee_id: Option<Uuid>,
    pub badge_code: Option<String>,
    pub pin_hash: Option<String>,
}

impl KioskPinFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.employee_id.is_some() || self.badge_code.is_some() || self.pin_hash.is_some()
    }
}

/// Repository trait for KioskPin aggregate
///
/// This trait defines the persistence contract for KioskPin entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait KioskPinRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new kiosk_pin entity
    async fn save(&self, entity: &KioskPin) -> Result<KioskPin>;

    /// Find kiosk_pin by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<KioskPin>>;

    /// Find all kiosk_pin entities
    async fn find_all(&self) -> Result<Vec<KioskPin>>;

    /// Update kiosk_pin by ID
    async fn update(&self, id: &str, entity: &KioskPin) -> Result<Option<KioskPin>>;

    /// Delete kiosk_pin by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List kiosk_pin with pagination
    async fn list(&self, params: KioskPinPaginationParams) -> Result<KioskPinPaginatedResult>;

    /// List kiosk_pin with pagination and filters
    async fn list_with_filters(&self, params: KioskPinPaginationParams, filters: KioskPinFilter) -> Result<KioskPinPaginatedResult>;

    /// Count all kiosk_pin entities
    async fn count(&self) -> Result<u64>;

    /// Count kiosk_pin entities matching filters
    async fn count_with_filters(&self, filters: KioskPinFilter) -> Result<u64>;

    /// Check if kiosk_pin exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete kiosk_pin by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted kiosk_pin by ID
    async fn restore(&self, id: &str) -> Result<Option<KioskPin>>;

    /// List soft-deleted kiosk_pin entities
    async fn list_deleted(&self, params: KioskPinPaginationParams) -> Result<KioskPinPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save kiosk_pin entities
    async fn bulk_save(&self, entities: &[KioskPin]) -> Result<Vec<KioskPin>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
