//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod attendance_repository;
pub mod attendance_clock_repository;

// Re-exports
pub use attendance_repository::{
    AttendanceRepository,
    AttendancePaginationParams,
    AttendancePaginatedResult,
    AttendanceFilter,
};
pub use attendance_clock_repository::{
    AttendanceClockRepository,
    AttendanceClockPaginationParams,
    AttendanceClockPaginatedResult,
    AttendanceClockFilter,
};
