//! Repository trait for OvertimeRequest aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the OvertimeRequest aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{OvertimeRequest, OvertimeRequestStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OvertimeRequestPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl OvertimeRequestPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct OvertimeRequestPaginatedResult {
    pub data: Vec<OvertimeRequest>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OvertimeRequestFilter {
    pub employee_id: Option<Uuid>,
    pub reason: Option<String>,
    pub status: Option<OvertimeRequestStatus>,
    pub approval_request_id: Option<Uuid>,
}

impl OvertimeRequestFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.employee_id.is_some() || self.reason.is_some() || self.status.is_some() || self.approval_request_id.is_some()
    }
}

/// Repository trait for OvertimeRequest aggregate
///
/// This trait defines the persistence contract for OvertimeRequest entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait OvertimeRequestRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new overtime_request entity
    async fn save(&self, entity: &OvertimeRequest) -> Result<OvertimeRequest>;

    /// Find overtime_request by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<OvertimeRequest>>;

    /// Find all overtime_request entities
    async fn find_all(&self) -> Result<Vec<OvertimeRequest>>;

    /// Update overtime_request by ID
    async fn update(&self, id: &str, entity: &OvertimeRequest) -> Result<Option<OvertimeRequest>>;

    /// Delete overtime_request by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List overtime_request with pagination
    async fn list(&self, params: OvertimeRequestPaginationParams) -> Result<OvertimeRequestPaginatedResult>;

    /// List overtime_request with pagination and filters
    async fn list_with_filters(&self, params: OvertimeRequestPaginationParams, filters: OvertimeRequestFilter) -> Result<OvertimeRequestPaginatedResult>;

    /// Count all overtime_request entities
    async fn count(&self) -> Result<u64>;

    /// Count overtime_request entities matching filters
    async fn count_with_filters(&self, filters: OvertimeRequestFilter) -> Result<u64>;

    /// Check if overtime_request exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete overtime_request by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted overtime_request by ID
    async fn restore(&self, id: &str) -> Result<Option<OvertimeRequest>>;

    /// List soft-deleted overtime_request entities
    async fn list_deleted(&self, params: OvertimeRequestPaginationParams) -> Result<OvertimeRequestPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save overtime_request entities
    async fn bulk_save(&self, entities: &[OvertimeRequest]) -> Result<Vec<OvertimeRequest>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
