//! Repository trait for RosterEntry aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the RosterEntry aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::RosterEntry;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct RosterEntryPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl RosterEntryPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct RosterEntryPaginatedResult {
    pub data: Vec<RosterEntry>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct RosterEntryFilter {
    pub employee_id: Option<Uuid>,
    pub shift_id: Option<Uuid>,
}

impl RosterEntryFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.employee_id.is_some() || self.shift_id.is_some()
    }
}

/// Repository trait for RosterEntry aggregate
///
/// This trait defines the persistence contract for RosterEntry entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait RosterEntryRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new roster_entry entity
    async fn save(&self, entity: &RosterEntry) -> Result<RosterEntry>;

    /// Find roster_entry by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<RosterEntry>>;

    /// Find all roster_entry entities
    async fn find_all(&self) -> Result<Vec<RosterEntry>>;

    /// Update roster_entry by ID
    async fn update(&self, id: &str, entity: &RosterEntry) -> Result<Option<RosterEntry>>;

    /// Delete roster_entry by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List roster_entry with pagination
    async fn list(&self, params: RosterEntryPaginationParams) -> Result<RosterEntryPaginatedResult>;

    /// List roster_entry with pagination and filters
    async fn list_with_filters(&self, params: RosterEntryPaginationParams, filters: RosterEntryFilter) -> Result<RosterEntryPaginatedResult>;

    /// Count all roster_entry entities
    async fn count(&self) -> Result<u64>;

    /// Count roster_entry entities matching filters
    async fn count_with_filters(&self, filters: RosterEntryFilter) -> Result<u64>;

    /// Check if roster_entry exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete roster_entry by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted roster_entry by ID
    async fn restore(&self, id: &str) -> Result<Option<RosterEntry>>;

    /// List soft-deleted roster_entry entities
    async fn list_deleted(&self, params: RosterEntryPaginationParams) -> Result<RosterEntryPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save roster_entry entities
    async fn bulk_save(&self, entities: &[RosterEntry]) -> Result<Vec<RosterEntry>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
