//! Repository for AttendanceSession entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<AttendanceSession, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::AttendanceSession;

/// Table name for AttendanceSession entities
pub const TABLE_NAME: &str = "attendance.attendance_sessions";

/// Repository for AttendanceSession entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct AttendanceSessionRepository(
    backbone_orm::GenericCrudRepository<AttendanceSession, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for AttendanceSessionRepository {
    type Target = backbone_orm::GenericCrudRepository<AttendanceSession, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl AttendanceSessionRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(AttendanceSessionRepository, AttendanceSession, soft_delete);
