//! Repository for AttendanceClock entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<AttendanceClock, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::AttendanceClock;

/// Table name for AttendanceClock entities
pub const TABLE_NAME: &str = "attendance.attendance_clocks";

/// Repository for AttendanceClock entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct AttendanceClockRepository(
    backbone_orm::GenericCrudRepository<AttendanceClock, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for AttendanceClockRepository {
    type Target = backbone_orm::GenericCrudRepository<AttendanceClock, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl AttendanceClockRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(AttendanceClockRepository, AttendanceClock, soft_delete);
