//! Repository for Attendance entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom method
//! below holds the hand-written Attendance read SQL (4-layer rule: services orchestrate, repos hold
//! SQL).
//!
//! Tenancy: none, by design (ADR-0029). No query here carries a tenant predicate — the reads are
//! scoped by the COMPOSING service's fence: when the request carries an ambient org scope it is
//! relayed onto a short read transaction, so the decorator's row-level rules govern what these
//! queries can see; unfenced deployments read the pool plain.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Attendance, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use chrono::NaiveDate;
use sqlx::PgPool;
use uuid::Uuid;

use backbone_orm::org_scope;

use crate::domain::entity::Attendance;

/// Table name for Attendance entities
pub const TABLE_NAME: &str = "attendance.attendances";

/// Repository for Attendance entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct AttendanceRepository(
    backbone_orm::GenericCrudRepository<Attendance, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for AttendanceRepository {
    type Target = backbone_orm::GenericCrudRepository<Attendance, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl AttendanceRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// Hand-written Attendance read SQL. Lives here (not in the query service) per the module's 4-layer
/// rule: services orchestrate, repositories hold the SQL.
impl AttendanceRepository {
    /// The dates in `[from, to]` (inclusive) on which the employee HAS an attendance record —
    /// i.e. was present. Attendance owns "presence"; absences are derived by the consumer
    /// (`absences = working_days − present_days − paid_leave_days`), so this deliberately does NOT
    /// join leave or schedule — attendance only.
    ///
    /// Read-only, tenant-agnostic (ADR-0029): takes the pool; when the request carries an ambient
    /// org scope it is relayed onto a short read transaction, so the composing service's fence
    /// applies (a foreign employee id simply matches zero rows); unfenced deployments read the
    /// pool plain. (backbone_orm's org scope offers no fetch-all helper, so the scoped path is a
    /// short read-only transaction here.)
    ///
    /// Soft-delete lives in the `metadata` JSONB column (`deleted_at` key); the `(metadata->>'deleted_at')
    /// IS NULL` predicate mirrors every other non-deleted read in this module.
    pub async fn present_days(
        &self,
        pool: &PgPool,
        employee_id: Uuid,
        from: NaiveDate,
        to: NaiveDate,
    ) -> Result<Vec<NaiveDate>, sqlx::Error> {
        // Decode the single DATE column as a 1-tuple row; `query_as::<_, (NaiveDate,)>` is
        // the documented shape for a single-column typed read.
        let query = sqlx::query_as::<_, (NaiveDate,)>(
            r#"SELECT date FROM attendance.attendances
               WHERE employee_id = $1
                 AND date BETWEEN $2 AND $3
                 AND (metadata->>'deleted_at') IS NULL
               ORDER BY date"#,
        )
        .bind(employee_id)
        .bind(from)
        .bind(to);

        let rows = if let Some(scope) = org_scope::current_org_scope() {
            let mut tx = pool.begin().await?;
            org_scope::bind_org_scope_on(&mut tx, &scope).await?;
            let rows = query.fetch_all(&mut *tx).await?;
            tx.commit().await?; // read-only: nothing but the relayed scope to close out
            rows
        } else {
            query.fetch_all(pool).await?
        };
        Ok(rows.into_iter().map(|(d,)| d).collect())
    }

    /// Overtime HOURS in `[from, to]` (inclusive): `SUM(time_debt->>'overtime_minutes') / 60` over
    /// the employee's live daily rollups. Attendance is the only writer of the `overtime_minutes`
    /// key (the shift-aware overlay stamps it into `time_debt`), so attendance is also the only
    /// reader that should interpret it — consumers get the finished number. `COALESCE` absorbs
    /// NULL keys (no overtime stamped) into zero, and `GREATEST(..., 0)` guards against a future
    /// writer stamping negative debt into the same field.
    ///
    /// Same read-only, tenant-agnostic posture as [`AttendanceRepository::present_days`]: pool +
    /// relayed ambient org scope (ADR-0029).
    pub async fn overtime_hours(
        &self,
        pool: &PgPool,
        employee_id: Uuid,
        from: NaiveDate,
        to: NaiveDate,
    ) -> Result<rust_decimal::Decimal, sqlx::Error> {
        // Decode the single NUMERIC column as a 1-tuple and unwrap (same shape as `present_days`).
        // A bare aggregate always yields exactly one row, so `fetch_one` matches both branches.
        let query = sqlx::query_as::<_, (rust_decimal::Decimal,)>(
            r#"SELECT GREATEST(
                   COALESCE(SUM((time_debt->>'overtime_minutes')::numeric), 0) / 60, 0)
               FROM attendance.attendances
               WHERE employee_id = $1
                 AND date BETWEEN $2 AND $3
                 AND (metadata->>'deleted_at') IS NULL"#,
        )
        .bind(employee_id)
        .bind(from)
        .bind(to);

        let (hours,) = if let Some(scope) = org_scope::current_org_scope() {
            let mut tx = pool.begin().await?;
            org_scope::bind_org_scope_on(&mut tx, &scope).await?;
            let row = query.fetch_one(&mut *tx).await?;
            tx.commit().await?; // read-only: nothing but the relayed scope to close out
            row
        } else {
            query.fetch_one(pool).await?
        };
        Ok(hours)
    }

    /// Per-day form of [`AttendanceRepository::overtime_hours`]: one `(date, hours)` row per
    /// date with overtime, `GROUP BY date` over the same predicates (employee, range,
    /// live rows). Returning per-day figures (not the window sum) keeps banded overtime pricing
    /// correct — the multiplier schedule resets with each day's stretch, so only a per-day walk
    /// prices every day's first hour at the opening band. Days with zero/negative debt are
    /// filtered out here so callers never see empty stretch entries.
    pub async fn overtime_stretches(
        &self,
        pool: &PgPool,
        employee_id: Uuid,
        from: NaiveDate,
        to: NaiveDate,
    ) -> Result<Vec<(NaiveDate, rust_decimal::Decimal)>, sqlx::Error> {
        let query = sqlx::query_as::<_, (NaiveDate, rust_decimal::Decimal)>(
            r#"SELECT date, GREATEST(SUM((time_debt->>'overtime_minutes')::numeric) / 60, 0)
               FROM attendance.attendances
               WHERE employee_id = $1
                 AND date BETWEEN $2 AND $3
                 AND (metadata->>'deleted_at') IS NULL
               GROUP BY date
               ORDER BY date"#,
        )
        .bind(employee_id)
        .bind(from)
        .bind(to);

        let mut rows = if let Some(scope) = org_scope::current_org_scope() {
            let mut tx = pool.begin().await?;
            org_scope::bind_org_scope_on(&mut tx, &scope).await?;
            let rows = query.fetch_all(&mut *tx).await?;
            tx.commit().await?; // read-only: nothing but the relayed scope to close out
            rows
        } else {
            query.fetch_all(pool).await?
        };
        rows.retain(|(_, hours)| *hours > rust_decimal::Decimal::ZERO);
        Ok(rows)
    }
}

backbone_core::impl_crud_repository!(AttendanceRepository, Attendance, soft_delete);
