//! Repository for Attendance entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom method
//! below holds the hand-written Attendance read SQL (4-layer rule: services orchestrate, repos hold
//! SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Attendance, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use chrono::NaiveDate;
use sqlx::PgPool;
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::Attendance;

/// Table name for Attendance entities
pub const TABLE_NAME: &str = "attendance.attendances";

/// Repository for Attendance entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct AttendanceRepository(
    backbone_orm::GenericCrudRepository<Attendance, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for AttendanceRepository {
    type Target = backbone_orm::GenericCrudRepository<Attendance, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl AttendanceRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// Hand-written Attendance read SQL. Lives here (not in the query service) per the module's 4-layer
/// rule: services orchestrate, repositories hold the SQL.
impl AttendanceRepository {
    /// The dates in `[from, to]` (inclusive) on which the employee HAS an attendance record —
    /// i.e. was present. Attendance owns "presence"; absences are derived by the consumer
    /// (`absences = working_days − present_days − paid_leave_days`), so this deliberately does NOT
    /// join leave or schedule — attendance only.
    ///
    /// Read-only, company-scoped: takes the pool and runs `fetch_all_scoped` so the RLS fence
    /// (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company_id))` (or the
    /// HTTP composition root's `with_request_scope`) — otherwise it fails closed (0 rows).
    ///
    /// Soft-delete lives in the `metadata` JSONB column (`deleted_at` key); the `(metadata->>'deleted_at')
    /// IS NULL` predicate mirrors every other non-deleted read in this module.
    pub async fn present_days(
        &self,
        pool: &PgPool,
        company_id: Uuid,
        employee_id: Uuid,
        from: NaiveDate,
        to: NaiveDate,
    ) -> Result<Vec<NaiveDate>, sqlx::Error> {
        // No `fetch_all_scalar_scoped` exists in backbone_orm, so decode the single DATE column as a
        // 1-tuple row via `fetch_all_scoped` and unwrap the tuple. `query_as::<_, (NaiveDate,)>` is
        // the documented shape for a single-column typed read.
        let rows: Vec<(NaiveDate,)> = company_scope::fetch_all_scoped(
            pool,
            sqlx::query_as(
                r#"SELECT date FROM attendance.attendances
                   WHERE company_id = $1
                     AND employee_id = $2
                     AND date BETWEEN $3 AND $4
                     AND (metadata->>'deleted_at') IS NULL
                   ORDER BY date"#,
            )
            .bind(company_id)
            .bind(employee_id)
            .bind(from)
            .bind(to),
        )
        .await?;
        Ok(rows.into_iter().map(|(d,)| d).collect())
    }

    /// Overtime HOURS in `[from, to]` (inclusive): `SUM(time_debt->>'overtime_minutes') / 60` over
    /// the employee's live daily rollups. Attendance is the only writer of the `overtime_minutes`
    /// key (the shift-aware overlay stamps it into `time_debt`), so attendance is also the only
    /// reader that should interpret it — consumers get the finished number. `COALESCE` absorbs
    /// NULL keys (no overtime stamped) into zero, and `GREATEST(..., 0)` guards against a future
    /// writer stamping negative debt into the same field.
    ///
    /// Same read-only, company-scoped posture as [`AttendanceRepository::present_days`]: pool +
    /// `fetch_one_scoped`, caller wraps in `with_company_scope` / `with_request_scope`.
    pub async fn overtime_hours(
        &self,
        pool: &PgPool,
        company_id: Uuid,
        employee_id: Uuid,
        from: NaiveDate,
        to: NaiveDate,
    ) -> Result<rust_decimal::Decimal, sqlx::Error> {
        // No `fetch_one_scalar_scoped` in backbone_orm — decode the single NUMERIC column as a
        // 1-tuple via `fetch_one_scoped` and unwrap (same shape as `present_days` above).
        let (hours,): (rust_decimal::Decimal,) = company_scope::fetch_one_scoped(
            pool,
            sqlx::query_as(
                r#"SELECT GREATEST(
                       COALESCE(SUM((time_debt->>'overtime_minutes')::numeric), 0) / 60, 0)
                   FROM attendance.attendances
                   WHERE company_id = $1
                     AND employee_id = $2
                     AND date BETWEEN $3 AND $4
                     AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(company_id)
            .bind(employee_id)
            .bind(from)
            .bind(to),
        )
        .await?;
        Ok(hours)
    }
}

backbone_core::impl_crud_repository!(AttendanceRepository, Attendance, soft_delete);
