//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod attendance_repository;
mod attendance_clock_repository;
mod attendance_correction_repository;
mod attendance_session_repository;
mod kiosk_pin_repository;
mod overtime_request_repository;
mod roster_entry_repository;
mod shift_repository;

// Custom persistence modules
// <<< CUSTOM
// Hand-written write SQL for the punch / session / kiosk-PIN flows (user-owned file).
mod attendance_write_repository;
// END CUSTOM

// Re-exports
pub use attendance_repository::AttendanceRepository;
pub use attendance_clock_repository::AttendanceClockRepository;
pub use attendance_correction_repository::AttendanceCorrectionRepository;
pub use attendance_session_repository::AttendanceSessionRepository;
pub use kiosk_pin_repository::KioskPinRepository;
pub use overtime_request_repository::OvertimeRequestRepository;
pub use roster_entry_repository::RosterEntryRepository;
pub use shift_repository::ShiftRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
pub use attendance_write_repository::{AttendanceWriteRepository, PinRow, SessionRow};
// END CUSTOM
