//! Repository for OvertimeRequest entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<OvertimeRequest, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::OvertimeRequest;

/// Table name for OvertimeRequest entities
pub const TABLE_NAME: &str = "attendance.overtime_requests";

/// Repository for OvertimeRequest entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct OvertimeRequestRepository(
    backbone_orm::GenericCrudRepository<OvertimeRequest, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for OvertimeRequestRepository {
    type Target = backbone_orm::GenericCrudRepository<OvertimeRequest, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl OvertimeRequestRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(OvertimeRequestRepository, OvertimeRequest, soft_delete);
