//! Repository for RosterEntry entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<RosterEntry, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::RosterEntry;

/// Table name for RosterEntry entities
pub const TABLE_NAME: &str = "attendance.roster_entries";

/// Repository for RosterEntry entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct RosterEntryRepository(
    backbone_orm::GenericCrudRepository<RosterEntry, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for RosterEntryRepository {
    type Target = backbone_orm::GenericCrudRepository<RosterEntry, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl RosterEntryRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(RosterEntryRepository, RosterEntry, soft_delete);
