//! Repository for Shift entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Shift, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Shift;

/// Table name for Shift entities
pub const TABLE_NAME: &str = "attendance.shifts";

/// Repository for Shift entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ShiftRepository(
    backbone_orm::GenericCrudRepository<Shift, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ShiftRepository {
    type Target = backbone_orm::GenericCrudRepository<Shift, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ShiftRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ShiftRepository, Shift, soft_delete);
