//! Validator for AttendanceCorrection entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<AttendanceCorrection>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::AttendanceCorrection;

/// Validator type alias for AttendanceCorrection entities.
pub type AttendanceCorrectionValidator = EntityValidator<AttendanceCorrection>;

/// Build a validator for AttendanceCorrection with all schema-defined field rules.
pub fn attendance_correction_validator() -> AttendanceCorrectionValidator {
    EntityValidator::new()
        .rule(RequiredString::new("reason", |e: &AttendanceCorrection| &e.reason))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
