//! Validator for AttendanceSession entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<AttendanceSession>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::AttendanceSession;

/// Validator type alias for AttendanceSession entities.
pub type AttendanceSessionValidator = EntityValidator<AttendanceSession>;

/// Build a validator for AttendanceSession with all schema-defined field rules.
pub fn attendance_session_validator() -> AttendanceSessionValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("correction_reason", |e: &AttendanceSession| e.correction_reason.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
