//! Validator for AttendanceClock entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<AttendanceClock>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::AttendanceClock;

/// Validator type alias for AttendanceClock entities.
pub type AttendanceClockValidator = EntityValidator<AttendanceClock>;

/// Build a validator for AttendanceClock with all schema-defined field rules.
pub fn attendance_clock_validator() -> AttendanceClockValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("device_ref", |e: &AttendanceClock| e.device_ref.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
