//! Validator for KioskPin entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<KioskPin>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::KioskPin;

/// Validator type alias for KioskPin entities.
pub type KioskPinValidator = EntityValidator<KioskPin>;

/// Build a validator for KioskPin with all schema-defined field rules.
pub fn kiosk_pin_validator() -> KioskPinValidator {
    EntityValidator::new()
        .rule(RequiredString::new("badge_code", |e: &KioskPin| &e.badge_code))
        .rule(RequiredString::new("pin_hash", |e: &KioskPin| &e.pin_hash))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
