//! Entity validators
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::{ValidationError, ValidationErrors, ValidationResult, EntityValidator};

pub mod attendance_validator;
pub mod attendance_clock_validator;

pub use attendance_validator::{AttendanceValidator, attendance_validator};
pub use attendance_clock_validator::{AttendanceClockValidator, attendance_clock_validator};

// <<< CUSTOM
// END CUSTOM
