//! Validator for OvertimeRequest entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<OvertimeRequest>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::OvertimeRequest;

/// Validator type alias for OvertimeRequest entities.
pub type OvertimeRequestValidator = EntityValidator<OvertimeRequest>;

/// Build a validator for OvertimeRequest with all schema-defined field rules.
pub fn overtime_request_validator() -> OvertimeRequestValidator {
    EntityValidator::new()
        .rule(RequiredString::new("reason", |e: &OvertimeRequest| &e.reason))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
