//! Validator for RosterEntry entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<RosterEntry>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::RosterEntry;

/// Validator type alias for RosterEntry entities.
pub type RosterEntryValidator = EntityValidator<RosterEntry>;

/// Build a validator for RosterEntry with all schema-defined field rules.
pub fn roster_entry_validator() -> RosterEntryValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
