//! Validator for Shift entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Shift>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::Shift;

/// Validator type alias for Shift entities.
pub type ShiftValidator = EntityValidator<Shift>;

/// Build a validator for Shift with all schema-defined field rules.
pub fn shift_validator() -> ShiftValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &Shift| &e.name))
        .rule(RequiredString::new("code", |e: &Shift| &e.code))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
