//! Auth configuration for AttendanceClock handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<AttendanceClock>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::AttendanceClockService;
use crate::domain::entity::AttendanceClock;

/// Permission string constants for AttendanceClock operations.
pub mod permissions {
    pub const LIST:        &str = "attendance_clock:list";
    pub const READ:        &str = "attendance_clock:read";
    pub const CREATE:      &str = "attendance_clock:create";
    pub const UPDATE:      &str = "attendance_clock:update";
    pub const DELETE:      &str = "attendance_clock:delete";
    pub const RESTORE:     &str = "attendance_clock:restore";
    pub const TRASH:       &str = "attendance_clock:trash";
    pub const EMPTY_TRASH: &str = "attendance_clock:empty_trash";
    pub const BULK_CREATE: &str = "attendance_clock:bulk_create";
    pub const UPSERT:      &str = "attendance_clock:upsert";
}

/// Resource policy for AttendanceClock — maps CRUD actions to permission strings.
pub struct AttendanceClockPolicy;

#[async_trait]
impl ResourcePolicy<AttendanceClock> for AttendanceClockPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &AttendanceClock,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for AttendanceClock handlers.
///
/// Wraps `AttendanceClockService` and checks `AttendanceClockPolicy` before delegating.
pub type AttendanceClockGuard = PermissionGuard<AttendanceClock>;

/// Service-integrated permission guard for AttendanceClock (for use in generated handlers).
pub type AttendanceClockServiceGuard = ServicePermissionGuard<AttendanceClock, AttendanceClockService, AttendanceClockPolicy>;

// <<< CUSTOM
// END CUSTOM
