//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod attendance_auth;
pub mod attendance_clock_auth;

pub use attendance_auth::{AttendancePolicy, AttendanceGuard, AttendanceServiceGuard};
pub use attendance_clock_auth::{AttendanceClockPolicy, AttendanceClockGuard, AttendanceClockServiceGuard};

// <<< CUSTOM
// END CUSTOM
