//! AttendanceCorrection API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the AttendanceCorrection CRUD API endpoints.

use chrono::Utc;
use crate::integration::framework::ApiTest;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ATTENDANCECORRECTION TEST DATA GENERATOR
// ============================================================================

/// Test data generator for AttendanceCorrection
pub struct AttendanceCorrectionTestData;

impl TestDataGenerator for AttendanceCorrectionTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "session_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "check_in": now,
            "check_out": null,
            "reason": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "status": "pending",
            "approval_request_id": null,
            "submitted_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "session_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "check_in": now,
            "check_out": null,
            "reason": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "status": "pending",
            "approval_request_id": null,
            "submitted_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/attendance_sessions", &super::attendance_session_api_test::AttendanceSessionTestData).await {
            deps.push(("session_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// ATTENDANCECORRECTION API TEST
// ============================================================================

/// AttendanceCorrection API test suite
pub struct AttendanceCorrectionApiTest {
    inner: GenericCrudTest<AttendanceCorrectionTestData>,
}

impl AttendanceCorrectionApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/attendance_corrections", "AttendanceCorrection");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, AttendanceCorrectionTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for AttendanceCorrectionApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_attendance_correction_crud() {
        let mut test = AttendanceCorrectionApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add AttendanceCorrection specific tests here
// <<< CUSTOM TESTS END >>>
