//! AttendanceClock API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the AttendanceClock CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ATTENDANCECLOCK TEST DATA GENERATOR
// ============================================================================

/// Test data generator for AttendanceClock
pub struct AttendanceClockTestData;

impl TestDataGenerator for AttendanceClockTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "session_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "date": Utc::now().format("%Y-%m-%d").to_string(),
            "punched_at": now,
            "direction": "in",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "session_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "date": Utc::now().format("%Y-%m-%d").to_string(),
            "punched_at": now,
            "direction": "in",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/attendance_sessions", &super::attendance_session_api_test::AttendanceSessionTestData).await {
            deps.push(("session_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// ATTENDANCECLOCK API TEST
// ============================================================================

/// AttendanceClock API test suite
pub struct AttendanceClockApiTest {
    inner: GenericCrudTest<AttendanceClockTestData>,
}

impl AttendanceClockApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/attendance_clocks", "AttendanceClock");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, AttendanceClockTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for AttendanceClockApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_attendance_clock_crud() {
        let mut test = AttendanceClockApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add AttendanceClock specific tests here
// <<< CUSTOM TESTS END >>>
