//! AttendanceSession API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the AttendanceSession CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ATTENDANCESESSION TEST DATA GENERATOR
// ============================================================================

/// Test data generator for AttendanceSession
pub struct AttendanceSessionTestData;

impl TestDataGenerator for AttendanceSessionTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "date": Utc::now().format("%Y-%m-%d").to_string(),
            "check_in": now,
            "check_out": null,
            "source": "kiosk",
            "correction_reason": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "employee_id": Uuid::new_v4().to_string(),
            "date": Utc::now().format("%Y-%m-%d").to_string(),
            "check_in": now,
            "check_out": null,
            "source": "kiosk",
            "correction_reason": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// ATTENDANCESESSION API TEST
// ============================================================================

/// AttendanceSession API test suite
pub struct AttendanceSessionApiTest {
    inner: GenericCrudTest<AttendanceSessionTestData>,
}

impl AttendanceSessionApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/attendance_sessions", "AttendanceSession");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, AttendanceSessionTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for AttendanceSessionApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_attendance_session_crud() {
        let mut test = AttendanceSessionApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add AttendanceSession specific tests here
// <<< CUSTOM TESTS END >>>
