//! KioskPin API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the KioskPin CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// KIOSKPIN TEST DATA GENERATOR
// ============================================================================

/// Test data generator for KioskPin
pub struct KioskPinTestData;

impl TestDataGenerator for KioskPinTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "badge_code": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "pin_hash": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "failed_attempts": 1,
            "locked_until": null,
            "last_attempt_at": now,
            "expires_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "employee_id": Uuid::new_v4().to_string(),
            "badge_code": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "pin_hash": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "failed_attempts": 1,
            "locked_until": null,
            "last_attempt_at": now,
            "expires_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// KIOSKPIN API TEST
// ============================================================================

/// KioskPin API test suite
pub struct KioskPinApiTest {
    inner: GenericCrudTest<KioskPinTestData>,
}

impl KioskPinApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/kiosk_pins", "KioskPin");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, KioskPinTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for KioskPinApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_kiosk_pin_crud() {
        let mut test = KioskPinApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add KioskPin specific tests here
// <<< CUSTOM TESTS END >>>
