//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod attendance_api_test;
pub mod attendance_clock_api_test;
pub mod attendance_session_api_test;
pub mod kiosk_pin_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use attendance_api_test::*;
pub use attendance_clock_api_test::*;
pub use attendance_session_api_test::*;
pub use kiosk_pin_api_test::*;
