//! OvertimeRequest API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the OvertimeRequest CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::helpers::CommonUtils;

// ============================================================================
// OVERTIMEREQUEST TEST DATA GENERATOR
// ============================================================================

/// Test data generator for OvertimeRequest
pub struct OvertimeRequestTestData;

impl TestDataGenerator for OvertimeRequestTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "date": Utc::now().format("%Y-%m-%d").to_string(),
            "hours_planned": 0,
            "reason": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "status": "pending",
            "approval_request_id": null,
            "decided_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "employee_id": Uuid::new_v4().to_string(),
            "date": Utc::now().format("%Y-%m-%d").to_string(),
            "hours_planned": 0,
            "reason": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "status": "pending",
            "approval_request_id": null,
            "decided_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// OVERTIMEREQUEST API TEST
// ============================================================================

/// OvertimeRequest API test suite
pub struct OvertimeRequestApiTest {
    inner: GenericCrudTest<OvertimeRequestTestData>,
}

impl OvertimeRequestApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/overtime_requests", "OvertimeRequest");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, OvertimeRequestTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for OvertimeRequestApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_overtime_request_crud() {
        let mut test = OvertimeRequestApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add OvertimeRequest specific tests here
// <<< CUSTOM TESTS END >>>
