//! Shift API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Shift CRUD API endpoints.

use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::helpers::CommonUtils;

// ============================================================================
// SHIFT TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Shift
pub struct ShiftTestData;

impl TestDataGenerator for ShiftTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        json!({
            "id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "start_time": null,
            "end_time": null,
            "break_minutes": null,
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        json!({
            "id": id,
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "code": format!("TEST_{}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "start_time": null,
            "end_time": null,
            "break_minutes": null,
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// SHIFT API TEST
// ============================================================================

/// Shift API test suite
pub struct ShiftApiTest {
    inner: GenericCrudTest<ShiftTestData>,
}

impl ShiftApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/shifts", "Shift");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, ShiftTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ShiftApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_shift_crud() {
        let mut test = ShiftApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Shift specific tests here
// <<< CUSTOM TESTS END >>>
