//! Attendance Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::AttendanceService;
use crate::application::service::AttendanceClockService;
use crate::application::service::AttendanceSessionService;
use crate::application::service::KioskPinService;
use crate::application::service::OvertimeRequestService;
use crate::application::service::RosterEntryService;
use crate::application::service::ShiftService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Attendance service
    pub attendance_service: Arc<AttendanceService>,
    /// AttendanceClock service
    pub attendance_clock_service: Arc<AttendanceClockService>,
    /// AttendanceSession service
    pub attendance_session_service: Arc<AttendanceSessionService>,
    /// KioskPin service
    pub kiosk_pin_service: Arc<KioskPinService>,
    /// OvertimeRequest service
    pub overtime_request_service: Arc<OvertimeRequestService>,
    /// RosterEntry service
    pub roster_entry_service: Arc<RosterEntryService>,
    /// Shift service
    pub shift_service: Arc<ShiftService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        attendance_service: Arc<AttendanceService>,
        attendance_clock_service: Arc<AttendanceClockService>,
        attendance_session_service: Arc<AttendanceSessionService>,
        kiosk_pin_service: Arc<KioskPinService>,
        overtime_request_service: Arc<OvertimeRequestService>,
        roster_entry_service: Arc<RosterEntryService>,
        shift_service: Arc<ShiftService>
    ) -> Self {
        Self {
            attendance_service,
            attendance_clock_service,
            attendance_session_service,
            kiosk_pin_service,
            overtime_request_service,
            roster_entry_service,
            shift_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::AttendanceModule) -> Self {
        Self {
            attendance_service: module.attendance_service.clone(),
            attendance_clock_service: module.attendance_clock_service.clone(),
            attendance_session_service: module.attendance_session_service.clone(),
            kiosk_pin_service: module.kiosk_pin_service.clone(),
            overtime_request_service: module.overtime_request_service.clone(),
            roster_entry_service: module.roster_entry_service.clone(),
            shift_service: module.shift_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    attendance_service: Option<Arc<AttendanceService>>,
    attendance_clock_service: Option<Arc<AttendanceClockService>>,
    attendance_session_service: Option<Arc<AttendanceSessionService>>,
    kiosk_pin_service: Option<Arc<KioskPinService>>,
    overtime_request_service: Option<Arc<OvertimeRequestService>>,
    roster_entry_service: Option<Arc<RosterEntryService>>,
    shift_service: Option<Arc<ShiftService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Attendance service.
    pub fn with_attendance_service(mut self, service: Arc<AttendanceService>) -> Self {
        self.attendance_service = Some(service);
        self
    }

    /// Set the AttendanceClock service.
    pub fn with_attendance_clock_service(mut self, service: Arc<AttendanceClockService>) -> Self {
        self.attendance_clock_service = Some(service);
        self
    }

    /// Set the AttendanceSession service.
    pub fn with_attendance_session_service(mut self, service: Arc<AttendanceSessionService>) -> Self {
        self.attendance_session_service = Some(service);
        self
    }

    /// Set the KioskPin service.
    pub fn with_kiosk_pin_service(mut self, service: Arc<KioskPinService>) -> Self {
        self.kiosk_pin_service = Some(service);
        self
    }

    /// Set the OvertimeRequest service.
    pub fn with_overtime_request_service(mut self, service: Arc<OvertimeRequestService>) -> Self {
        self.overtime_request_service = Some(service);
        self
    }

    /// Set the RosterEntry service.
    pub fn with_roster_entry_service(mut self, service: Arc<RosterEntryService>) -> Self {
        self.roster_entry_service = Some(service);
        self
    }

    /// Set the Shift service.
    pub fn with_shift_service(mut self, service: Arc<ShiftService>) -> Self {
        self.shift_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            attendance_service: self.attendance_service.expect("attendance_service is required"),
            attendance_clock_service: self.attendance_clock_service.expect("attendance_clock_service is required"),
            attendance_session_service: self.attendance_session_service.expect("attendance_session_service is required"),
            kiosk_pin_service: self.kiosk_pin_service.expect("kiosk_pin_service is required"),
            overtime_request_service: self.overtime_request_service.expect("overtime_request_service is required"),
            roster_entry_service: self.roster_entry_service.expect("roster_entry_service is required"),
            shift_service: self.shift_service.expect("shift_service is required"),
        }
    }
}
