//! Attendance Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::AttendanceService;
use crate::application::service::AttendanceClockService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Attendance service
    pub attendance_service: Arc<AttendanceService>,
    /// AttendanceClock service
    pub attendance_clock_service: Arc<AttendanceClockService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        attendance_service: Arc<AttendanceService>,
        attendance_clock_service: Arc<AttendanceClockService>
    ) -> Self {
        Self {
            attendance_service,
            attendance_clock_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::AttendanceModule) -> Self {
        Self {
            attendance_service: module.attendance_service.clone(),
            attendance_clock_service: module.attendance_clock_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    attendance_service: Option<Arc<AttendanceService>>,
    attendance_clock_service: Option<Arc<AttendanceClockService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Attendance service.
    pub fn with_attendance_service(mut self, service: Arc<AttendanceService>) -> Self {
        self.attendance_service = Some(service);
        self
    }

    /// Set the AttendanceClock service.
    pub fn with_attendance_clock_service(mut self, service: Arc<AttendanceClockService>) -> Self {
        self.attendance_clock_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            attendance_service: self.attendance_service.expect("attendance_service is required"),
            attendance_clock_service: self.attendance_clock_service.expect("attendance_clock_service is required"),
        }
    }
}
