//! Saga / orchestration workflows
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! No workflows are defined for this module yet. Add saga/orchestration
//! flows here as `*_workflow.rs` siblings when needed.
