//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    attendance_handler::create_attendance_routes,
    attendance_clock_handler::create_attendance_clock_routes,
    attendance_session_handler::create_attendance_session_routes,
    kiosk_pin_handler::create_kiosk_pin_routes,
};

use crate::application::service::{
    AttendanceService,
    AttendanceClockService,
    AttendanceSessionService,
    KioskPinService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub attendance: Arc<AttendanceService>,
    pub attendance_clock: Arc<AttendanceClockService>,
    pub attendance_session: Arc<AttendanceSessionService>,
    pub kiosk_pin: Arc<KioskPinService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // Attendance routes (12 Backbone endpoints)
        .merge(create_attendance_routes(services.attendance))
        // AttendanceClock routes (12 Backbone endpoints)
        .merge(create_attendance_clock_routes(services.attendance_clock))
        // AttendanceSession routes (12 Backbone endpoints)
        .merge(create_attendance_session_routes(services.attendance_session))
        // KioskPin routes (12 Backbone endpoints)
        .merge(create_kiosk_pin_routes(services.kiosk_pin))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn attendance_routes(service: Arc<AttendanceService>) -> Router {
        create_attendance_routes(service)
    }

    pub fn attendance_clock_routes(service: Arc<AttendanceClockService>) -> Router {
        create_attendance_clock_routes(service)
    }

    pub fn attendance_session_routes(service: Arc<AttendanceSessionService>) -> Router {
        create_attendance_session_routes(service)
    }

    pub fn kiosk_pin_routes(service: Arc<KioskPinService>) -> Router {
        create_kiosk_pin_routes(service)
    }

}
