//! Public events for Attendance module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// ATTENDANCE EVENTS
// ============================================================================

/// Event published when a Attendance is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceCreatedEvent {
    pub id: AttendanceId,
    pub data: AttendanceDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Attendance is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceUpdatedEvent {
    pub id: AttendanceId,
    pub data: AttendanceDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Attendance is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceDeletedEvent {
    pub id: AttendanceId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// ATTENDANCECLOCK EVENTS
// ============================================================================

/// Event published when a AttendanceClock is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceClockCreatedEvent {
    pub id: AttendanceClockId,
    pub data: AttendanceClockDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AttendanceClock is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceClockUpdatedEvent {
    pub id: AttendanceClockId,
    pub data: AttendanceClockDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AttendanceClock is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceClockDeletedEvent {
    pub id: AttendanceClockId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// ATTENDANCESESSION EVENTS
// ============================================================================

/// Event published when a AttendanceSession is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceSessionCreatedEvent {
    pub id: AttendanceSessionId,
    pub data: AttendanceSessionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AttendanceSession is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceSessionUpdatedEvent {
    pub id: AttendanceSessionId,
    pub data: AttendanceSessionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AttendanceSession is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceSessionDeletedEvent {
    pub id: AttendanceSessionId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// KIOSKPIN EVENTS
// ============================================================================

/// Event published when a KioskPin is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KioskPinCreatedEvent {
    pub id: KioskPinId,
    pub data: KioskPinDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a KioskPin is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KioskPinUpdatedEvent {
    pub id: KioskPinId,
    pub data: KioskPinDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a KioskPin is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KioskPinDeletedEvent {
    pub id: KioskPinId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Attendance module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum AttendanceEvent {
    AttendanceCreated(AttendanceCreatedEvent),
    AttendanceUpdated(AttendanceUpdatedEvent),
    AttendanceDeleted(AttendanceDeletedEvent),
    AttendanceClockCreated(AttendanceClockCreatedEvent),
    AttendanceClockUpdated(AttendanceClockUpdatedEvent),
    AttendanceClockDeleted(AttendanceClockDeletedEvent),
    AttendanceSessionCreated(AttendanceSessionCreatedEvent),
    AttendanceSessionUpdated(AttendanceSessionUpdatedEvent),
    AttendanceSessionDeleted(AttendanceSessionDeletedEvent),
    KioskPinCreated(KioskPinCreatedEvent),
    KioskPinUpdated(KioskPinUpdatedEvent),
    KioskPinDeleted(KioskPinDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for AttendanceEventMetadata {
    fn default() -> Self {
        Self {
            module: "attendance",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
