//! Public events for Attendance module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// ATTENDANCE EVENTS
// ============================================================================

/// Event published when a Attendance is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceCreatedEvent {
    pub id: AttendanceId,
    pub data: AttendanceDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Attendance is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceUpdatedEvent {
    pub id: AttendanceId,
    pub data: AttendanceDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Attendance is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceDeletedEvent {
    pub id: AttendanceId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// ATTENDANCECLOCK EVENTS
// ============================================================================

/// Event published when a AttendanceClock is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceClockCreatedEvent {
    pub id: AttendanceClockId,
    pub data: AttendanceClockDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AttendanceClock is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceClockUpdatedEvent {
    pub id: AttendanceClockId,
    pub data: AttendanceClockDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AttendanceClock is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceClockDeletedEvent {
    pub id: AttendanceClockId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// ATTENDANCESESSION EVENTS
// ============================================================================

/// Event published when a AttendanceSession is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceSessionCreatedEvent {
    pub id: AttendanceSessionId,
    pub data: AttendanceSessionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AttendanceSession is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceSessionUpdatedEvent {
    pub id: AttendanceSessionId,
    pub data: AttendanceSessionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AttendanceSession is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceSessionDeletedEvent {
    pub id: AttendanceSessionId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// KIOSKPIN EVENTS
// ============================================================================

/// Event published when a KioskPin is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KioskPinCreatedEvent {
    pub id: KioskPinId,
    pub data: KioskPinDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a KioskPin is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KioskPinUpdatedEvent {
    pub id: KioskPinId,
    pub data: KioskPinDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a KioskPin is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KioskPinDeletedEvent {
    pub id: KioskPinId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// OVERTIMEREQUEST EVENTS
// ============================================================================

/// Event published when a OvertimeRequest is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OvertimeRequestCreatedEvent {
    pub id: OvertimeRequestId,
    pub data: OvertimeRequestDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a OvertimeRequest is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OvertimeRequestUpdatedEvent {
    pub id: OvertimeRequestId,
    pub data: OvertimeRequestDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a OvertimeRequest is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OvertimeRequestDeletedEvent {
    pub id: OvertimeRequestId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// ROSTERENTRY EVENTS
// ============================================================================

/// Event published when a RosterEntry is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RosterEntryCreatedEvent {
    pub id: RosterEntryId,
    pub data: RosterEntryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a RosterEntry is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RosterEntryUpdatedEvent {
    pub id: RosterEntryId,
    pub data: RosterEntryDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a RosterEntry is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RosterEntryDeletedEvent {
    pub id: RosterEntryId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SHIFT EVENTS
// ============================================================================

/// Event published when a Shift is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShiftCreatedEvent {
    pub id: ShiftId,
    pub data: ShiftDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Shift is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShiftUpdatedEvent {
    pub id: ShiftId,
    pub data: ShiftDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Shift is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShiftDeletedEvent {
    pub id: ShiftId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Attendance module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum AttendanceEvent {
    AttendanceCreated(AttendanceCreatedEvent),
    AttendanceUpdated(AttendanceUpdatedEvent),
    AttendanceDeleted(AttendanceDeletedEvent),
    AttendanceClockCreated(AttendanceClockCreatedEvent),
    AttendanceClockUpdated(AttendanceClockUpdatedEvent),
    AttendanceClockDeleted(AttendanceClockDeletedEvent),
    AttendanceSessionCreated(AttendanceSessionCreatedEvent),
    AttendanceSessionUpdated(AttendanceSessionUpdatedEvent),
    AttendanceSessionDeleted(AttendanceSessionDeletedEvent),
    KioskPinCreated(KioskPinCreatedEvent),
    KioskPinUpdated(KioskPinUpdatedEvent),
    KioskPinDeleted(KioskPinDeletedEvent),
    OvertimeRequestCreated(OvertimeRequestCreatedEvent),
    OvertimeRequestUpdated(OvertimeRequestUpdatedEvent),
    OvertimeRequestDeleted(OvertimeRequestDeletedEvent),
    RosterEntryCreated(RosterEntryCreatedEvent),
    RosterEntryUpdated(RosterEntryUpdatedEvent),
    RosterEntryDeleted(RosterEntryDeletedEvent),
    ShiftCreated(ShiftCreatedEvent),
    ShiftUpdated(ShiftUpdatedEvent),
    ShiftDeleted(ShiftDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for AttendanceEventMetadata {
    fn default() -> Self {
        Self {
            module: "attendance",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
