//! Attendance Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Attendance exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use attendance::exports::{AttendanceDto, AttendanceQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `AttendanceDto` - Data transfer object for Attendance
/// - `AttendanceSummary` - Summary view of Attendance
/// - `AttendanceId` - Type-safe ID wrapper
/// - `AttendanceClockDto` - Data transfer object for AttendanceClock
/// - `AttendanceClockSummary` - Summary view of AttendanceClock
/// - `AttendanceClockId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `AttendanceQueryService` - Read-only queries
///
/// ## Public Events
/// - `AttendanceCreatedEvent` - Published when Attendance is created
/// - `AttendanceUpdatedEvent` - Published when Attendance is updated
/// - `AttendanceDeletedEvent` - Published when Attendance is deleted
/// - `AttendanceClockCreatedEvent` - Published when AttendanceClock is created
/// - `AttendanceClockUpdatedEvent` - Published when AttendanceClock is updated
/// - `AttendanceClockDeletedEvent` - Published when AttendanceClock is deleted
pub struct ExportSummary;
