//! Attendance Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Attendance exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use attendance::exports::{AttendanceDto};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `AttendanceDto` - Data transfer object for Attendance
/// - `AttendanceSummary` - Summary view of Attendance
/// - `AttendanceId` - Type-safe ID wrapper
/// - `AttendanceClockDto` - Data transfer object for AttendanceClock
/// - `AttendanceClockSummary` - Summary view of AttendanceClock
/// - `AttendanceClockId` - Type-safe ID wrapper
/// - `AttendanceSessionDto` - Data transfer object for AttendanceSession
/// - `AttendanceSessionSummary` - Summary view of AttendanceSession
/// - `AttendanceSessionId` - Type-safe ID wrapper
/// - `KioskPinDto` - Data transfer object for KioskPin
/// - `KioskPinSummary` - Summary view of KioskPin
/// - `KioskPinId` - Type-safe ID wrapper
/// - `OvertimeRequestDto` - Data transfer object for OvertimeRequest
/// - `OvertimeRequestSummary` - Summary view of OvertimeRequest
/// - `OvertimeRequestId` - Type-safe ID wrapper
/// - `RosterEntryDto` - Data transfer object for RosterEntry
/// - `RosterEntrySummary` - Summary view of RosterEntry
/// - `RosterEntryId` - Type-safe ID wrapper
/// - `ShiftDto` - Data transfer object for Shift
/// - `ShiftSummary` - Summary view of Shift
/// - `ShiftId` - Type-safe ID wrapper
///
/// ## Public Events
/// - `AttendanceCreatedEvent` - Published when Attendance is created
/// - `AttendanceUpdatedEvent` - Published when Attendance is updated
/// - `AttendanceDeletedEvent` - Published when Attendance is deleted
/// - `AttendanceClockCreatedEvent` - Published when AttendanceClock is created
/// - `AttendanceClockUpdatedEvent` - Published when AttendanceClock is updated
/// - `AttendanceClockDeletedEvent` - Published when AttendanceClock is deleted
/// - `AttendanceSessionCreatedEvent` - Published when AttendanceSession is created
/// - `AttendanceSessionUpdatedEvent` - Published when AttendanceSession is updated
/// - `AttendanceSessionDeletedEvent` - Published when AttendanceSession is deleted
/// - `KioskPinCreatedEvent` - Published when KioskPin is created
/// - `KioskPinUpdatedEvent` - Published when KioskPin is updated
/// - `KioskPinDeletedEvent` - Published when KioskPin is deleted
/// - `OvertimeRequestCreatedEvent` - Published when OvertimeRequest is created
/// - `OvertimeRequestUpdatedEvent` - Published when OvertimeRequest is updated
/// - `OvertimeRequestDeletedEvent` - Published when OvertimeRequest is deleted
/// - `RosterEntryCreatedEvent` - Published when RosterEntry is created
/// - `RosterEntryUpdatedEvent` - Published when RosterEntry is updated
/// - `RosterEntryDeletedEvent` - Published when RosterEntry is deleted
/// - `ShiftCreatedEvent` - Published when Shift is created
/// - `ShiftUpdatedEvent` - Published when Shift is updated
/// - `ShiftDeletedEvent` - Published when Shift is deleted
pub struct ExportSummary;
