//! Public services for Attendance module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use anyhow::Result;
use async_trait::async_trait;
use chrono::NaiveDate;
use rust_decimal::Decimal;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Attendance module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait AttendanceQueryService: Send + Sync {
    /// Get Attendance by ID
    async fn get_attendance(&self, id: AttendanceId) -> Result<Option<AttendanceDto>>;

    /// Get Attendance summary by ID
    async fn get_attendance_summary(&self, id: AttendanceId) -> Result<Option<AttendanceSummary>>;

    /// Check if Attendance exists
    async fn attendance_exists(&self, id: AttendanceId) -> Result<bool>;

    /// Get AttendanceClock by ID
    async fn get_attendance_clock(&self, id: AttendanceClockId) -> Result<Option<AttendanceClockDto>>;

    /// Get AttendanceClock summary by ID
    async fn get_attendance_clock_summary(&self, id: AttendanceClockId) -> Result<Option<AttendanceClockSummary>>;

    /// Check if AttendanceClock exists
    async fn attendance_clock_exists(&self, id: AttendanceClockId) -> Result<bool>;

    /// The dates in `[from, to]` (inclusive) on which the employee HAS an attendance record —
    /// i.e. was present. Attendance owns "presence"; absences are derived by the consumer
    /// (`absences = working_days − present_days − paid_leave_days`), so this does NOT join leave
    /// or schedule — attendance only.
    ///
    /// `company_id` is a LEGACY TWIN (ADR-0029): the module carries no tenant key, so the
    /// argument is accepted for compatibility with unstripped consumers and IGNORED — it never
    /// scopes the read. Row visibility follows the composing service's org fence.
    async fn present_days(
        &self,
        company_id: Uuid,
        employee_id: Uuid,
        from: NaiveDate,
        to: NaiveDate,
    ) -> Result<Vec<NaiveDate>>;

    /// Overtime HOURS worked in `[from, to]` (inclusive) — the sum of the daily rollups'
    /// `time_debt.overtime_minutes`, converted to hours. Attendance owns the `time_debt` JSON
    /// semantics because it is the only writer of that key; consumers get one number and never
    /// parse the JSON themselves. Days without overtime (or before any shift-aware overlay has
    /// stamped the key) contribute zero, so this degrades to 0 — never negative, never an error.
    ///
    /// The read is scoped by the composing service's org fence. It carried a legacy company
    /// argument for compatibility through the tenancy sweep; that argument is gone, because an
    /// ignored parameter is a standing invitation to pass the wrong thing.
    async fn overtime_hours(
        &self,
        company_id: Uuid,
        employee_id: Uuid,
        from: NaiveDate,
        to: NaiveDate,
    ) -> Result<Decimal>;

    /// The same overtime data as [`AttendanceQueryService::overtime_hours`], but PER DAY:
    /// one `(date, hours)` pair per date with overtime, ordered by date. Banded pricing
    /// schedules (an overtime multiplier that resets with each day's first hour) are only
    /// correct per day — a window-summed figure prices the period's first hour at the opening
    /// band and mis-prices every one-hour-per-day pattern — so consumers that price overtime
    /// against a band table must use this form. Empty when the employee has no overtime days
    /// in range; never negative, never an error.
    ///
    /// `company_id` is a LEGACY TWIN (ADR-0029): accepted for compatibility, ignored — the read
    /// is scoped by the composing service's org fence, never by this argument.
    async fn overtime_stretches(
        &self,
        employee_id: Uuid,
        from: NaiveDate,
        to: NaiveDate,
    ) -> Result<Vec<(NaiveDate, Decimal)>>;

}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
