//! Public services for Attendance module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use anyhow::Result;
use async_trait::async_trait;
use chrono::NaiveDate;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Attendance module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait AttendanceQueryService: Send + Sync {
    /// Get Attendance by ID
    async fn get_attendance(&self, id: AttendanceId) -> Result<Option<AttendanceDto>>;

    /// Get Attendance summary by ID
    async fn get_attendance_summary(&self, id: AttendanceId) -> Result<Option<AttendanceSummary>>;

    /// Check if Attendance exists
    async fn attendance_exists(&self, id: AttendanceId) -> Result<bool>;

    /// Get AttendanceClock by ID
    async fn get_attendance_clock(&self, id: AttendanceClockId) -> Result<Option<AttendanceClockDto>>;

    /// Get AttendanceClock summary by ID
    async fn get_attendance_clock_summary(&self, id: AttendanceClockId) -> Result<Option<AttendanceClockSummary>>;

    /// Check if AttendanceClock exists
    async fn attendance_clock_exists(&self, id: AttendanceClockId) -> Result<bool>;

    /// The dates in `[from, to]` (inclusive) on which the employee HAS an attendance record —
    /// i.e. was present. Attendance owns "presence"; absences are derived by the consumer
    /// (`absences = working_days − present_days − paid_leave_days`), so this does NOT join leave
    /// or schedule — attendance only. Company-scoped via RLS.
    async fn present_days(
        &self,
        company_id: Uuid,
        employee_id: Uuid,
        from: NaiveDate,
        to: NaiveDate,
    ) -> Result<Vec<NaiveDate>>;

}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
