//! Public types for Attendance module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate, NaiveTime};
use crate::domain::entity::*;

// ============================================================================
// ATTENDANCE TYPES
// ============================================================================

/// Type-safe ID for Attendance
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct AttendanceId(pub Uuid);

impl AttendanceId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for AttendanceId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<AttendanceId> for Uuid {
    fn from(id: AttendanceId) -> Self {
        id.0
    }
}

/// Data transfer object for Attendance
///
/// This is the public representation of Attendance for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceDto {
    pub id: AttendanceId,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub date: NaiveDate,
    pub schedule: Option<serde_json::Value>,
    pub clockin: Option<NaiveTime>,
    pub clockout: Option<NaiveTime>,
    pub time_debt: Option<serde_json::Value>,
    pub timeoff: Option<serde_json::Value>,
    pub metadata: serde_json::Value,
}

/// Summary view of Attendance for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceSummary {
    pub id: AttendanceId,
}

/// Reference to Attendance for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceRef {
    pub id: AttendanceId,
}

// ============================================================================
// ATTENDANCECLOCK TYPES
// ============================================================================

/// Type-safe ID for AttendanceClock
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct AttendanceClockId(pub Uuid);

impl AttendanceClockId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for AttendanceClockId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<AttendanceClockId> for Uuid {
    fn from(id: AttendanceClockId) -> Self {
        id.0
    }
}

/// Data transfer object for AttendanceClock
///
/// This is the public representation of AttendanceClock for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceClockDto {
    pub id: AttendanceClockId,
    pub company_id: Uuid,
    pub attendance_id: Uuid,
    pub employee_id: Uuid,
    pub date: NaiveDate,
    pub clock: NaiveTime,
    pub metadata: serde_json::Value,
}

/// Summary view of AttendanceClock for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceClockSummary {
    pub id: AttendanceClockId,
}

/// Reference to AttendanceClock for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttendanceClockRef {
    pub id: AttendanceClockId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
