//! Attendance Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::AttendanceService;
pub use application::service::AttendanceClockService;
pub use application::service::AttendanceSessionService;
pub use application::service::KioskPinService;

// Re-exports - Workflows
pub use application::workflows::*;

// <<< CUSTOM
// The validated write path (punch/session/kiosk-PIN — H-3) and its guarded HTTP composition.
pub use application::service::{
    validate_punch_time,
    lockout_until, pin_is_wellformed, AttendanceWriteError, AttendanceWriteService, PunchOutcome,
};
pub use presentation::http::create_guarded_attendance_routes;
// END CUSTOM
use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Attendance module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let attendance = AttendanceModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = attendance.all_crud_routes();
/// ```
pub struct AttendanceModule {
    pub(crate) attendance_service: Arc<AttendanceService>,
    pub(crate) attendance_clock_service: Arc<AttendanceClockService>,
    pub(crate) attendance_session_service: Arc<AttendanceSessionService>,
    pub(crate) kiosk_pin_service: Arc<KioskPinService>,
    // <<< CUSTOM FIELDS
    // Held so the `AttendanceQueryService` impl can delegate `present_days` to the repo's
    // hand-written SQL, and standard lookups to the CRUD services above. `db_pool` is the same pool
    // the repo was constructed with (the repo's present-days reads ride the ambient request
    // scope the composing service binds, per the backbone-hr read-port convention).
    pub(crate) attendance_repository: Arc<AttendanceRepository>,
    pub(crate) db_pool: sqlx::PgPool,
    // END CUSTOM
    // <<< CUSTOM FIELDS
    /// Validated punch/session/kiosk-PIN writes (EXCLUDE-overlap mapping, Tier B PIN policy,
    /// immutable clock events, daily rollup upsert). The guarded routes compose off this.
    pub attendance_write_service: Arc<AttendanceWriteService>,
    // END CUSTOM
}

impl AttendanceModule {
    /// Create a new module builder
    pub fn builder() -> AttendanceModuleBuilder {
        AttendanceModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_attendance_routes,
            create_attendance_clock_routes,
            create_attendance_session_routes,
            create_kiosk_pin_routes,
        };

        Router::new()
            .merge(create_attendance_routes(self.attendance_service.clone()))
            .merge(create_attendance_clock_routes(self.attendance_clock_service.clone()))
            .merge(create_attendance_session_routes(self.attendance_session_service.clone()))
            .merge(create_kiosk_pin_routes(self.kiosk_pin_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD; prefer readonly_routes() + validated writes, or all_crud_routes() for the full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }

    /// Read-only routes for every entity (GET endpoints only) — the safe base.
    ///
    /// Generic mutation can't reach here, so this surface cannot bypass a
    /// validated write service's invariants. Use this as the production base and
    /// merge validated write routes (or a write service's HTTP layer) onto it.
    pub fn readonly_routes(&self) -> Router {
        use presentation::http::{
            create_attendance_read_routes,
            create_attendance_clock_read_routes,
            create_attendance_session_read_routes,
            create_kiosk_pin_read_routes,
        };

        Router::new()
            .merge(create_attendance_read_routes(self.attendance_service.clone()))
            .merge(create_attendance_clock_read_routes(self.attendance_clock_service.clone()))
            .merge(create_attendance_session_read_routes(self.attendance_session_service.clone()))
            .merge(create_kiosk_pin_read_routes(self.kiosk_pin_service.clone()))
    }

    // <<< CUSTOM METHODS
    // END CUSTOM
}

/// Builder for AttendanceModule
pub struct AttendanceModuleBuilder {
    db_pool: Option<PgPool>,
}

impl AttendanceModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<AttendanceModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Attendance service
        let attendance_repository = Arc::new(AttendanceRepository::new(db_pool.clone()));
        let attendance_service = Arc::new(AttendanceService::with_repository(attendance_repository.clone()));

        // AttendanceClock service
        let attendance_clock_repository = Arc::new(AttendanceClockRepository::new(db_pool.clone()));
        let attendance_clock_service = Arc::new(AttendanceClockService::with_repository(attendance_clock_repository.clone()));

        // AttendanceSession service
        let attendance_session_repository = Arc::new(AttendanceSessionRepository::new(db_pool.clone()));
        let attendance_session_service = Arc::new(AttendanceSessionService::with_repository(attendance_session_repository.clone()));

        // KioskPin service
        let kiosk_pin_repository = Arc::new(KioskPinRepository::new(db_pool.clone()));
        let kiosk_pin_service = Arc::new(KioskPinService::with_repository(kiosk_pin_repository.clone()));

        // <<< CUSTOM
        let attendance_write_service = Arc::new(AttendanceWriteService::new(db_pool.clone()));
        // END CUSTOM

        Ok(AttendanceModule {
            attendance_service,
            attendance_clock_service,
            attendance_session_service,
            kiosk_pin_service,
            // <<< CUSTOM
            attendance_repository: attendance_repository.clone(),
            db_pool,
            // END CUSTOM
            // <<< CUSTOM
            attendance_write_service,
            // END CUSTOM
        })
    }
}

impl Default for AttendanceModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
