//! Attendance Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::AttendanceService;
pub use application::service::AttendanceClockService;

// Re-exports - Workflows
pub use application::workflows::*;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Attendance module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let attendance = AttendanceModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = attendance.all_crud_routes();
/// ```
pub struct AttendanceModule {
    pub(crate) attendance_service: Arc<AttendanceService>,
    pub(crate) attendance_clock_service: Arc<AttendanceClockService>,
    // <<< CUSTOM FIELDS
    // Held so the `AttendanceQueryService` impl can delegate `present_days` to the repo's
    // hand-written SQL, and standard lookups to the CRUD services above. `db_pool` is the same pool
    // the repo was constructed with (the repo's `present_days` takes it per the backbone-hr read-port
    // convention — RLS scoping is applied inside via `company_scope::fetch_all_scoped`).
    pub(crate) attendance_repository: Arc<AttendanceRepository>,
    pub(crate) db_pool: sqlx::PgPool,
    // END CUSTOM
}

impl AttendanceModule {
    /// Create a new module builder
    pub fn builder() -> AttendanceModuleBuilder {
        AttendanceModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_attendance_routes,
            create_attendance_clock_routes,
        };

        Router::new()
            .merge(create_attendance_routes(self.attendance_service.clone()))
            .merge(create_attendance_clock_routes(self.attendance_clock_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD on every entity; compose a guarded router for production, or call all_crud_routes() for the intentional full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }
}

/// Builder for AttendanceModule
pub struct AttendanceModuleBuilder {
    db_pool: Option<PgPool>,
}

impl AttendanceModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<AttendanceModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Attendance service
        let attendance_repository = Arc::new(AttendanceRepository::new(db_pool.clone()));
        let attendance_service = Arc::new(AttendanceService::with_repository(attendance_repository.clone()));

        // AttendanceClock service
        let attendance_clock_repository = Arc::new(AttendanceClockRepository::new(db_pool.clone()));
        let attendance_clock_service = Arc::new(AttendanceClockService::with_repository(attendance_clock_repository.clone()));

        // <<< CUSTOM
        // Retain the attendance repo + pool on the module so the `AttendanceQueryService` impl can
        // delegate `present_days` (custom SQL on the repo) and supply the pool the repo method takes.
        // END CUSTOM

        Ok(AttendanceModule {
            attendance_service,
            attendance_clock_service,
            // <<< CUSTOM
            attendance_repository: attendance_repository.clone(),
            db_pool,
            // END CUSTOM
        })
    }
}

impl Default for AttendanceModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
