//! Use case type aliases for AttendanceClock aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateAttendanceClockDto, UpdateAttendanceClockDto};
use crate::application::service::AttendanceClockService;
use crate::domain::entity::AttendanceClock;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateAttendanceClockUseCase = CreateUseCase<AttendanceClock, CreateAttendanceClockDto, AttendanceClockService>;
pub type UpdateAttendanceClockUseCase = UpdateUseCase<AttendanceClock, UpdateAttendanceClockDto, AttendanceClockService>;
pub type GetAttendanceClockUseCase    = GetUseCase<AttendanceClock, AttendanceClockService>;
pub type DeleteAttendanceClockUseCase = DeleteUseCase<AttendanceClock, AttendanceClockService>;
pub type ListAttendanceClockUseCase   = ListUseCase<AttendanceClock, AttendanceClockService>;

// <<< CUSTOM
// END CUSTOM
