//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod attendance_usecases;
pub mod attendance_clock_usecases;

pub use attendance_usecases::{
    CreateAttendanceUseCase, UpdateAttendanceUseCase, GetAttendanceUseCase,
    DeleteAttendanceUseCase, ListAttendanceUseCase,
};
pub use attendance_clock_usecases::{
    CreateAttendanceClockUseCase, UpdateAttendanceClockUseCase, GetAttendanceClockUseCase,
    DeleteAttendanceClockUseCase, ListAttendanceClockUseCase,
};

// <<< CUSTOM
// END CUSTOM
