//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod attendance_handler;
pub mod attendance_clock_handler;

// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use attendance_handler::{create_attendance_routes, create_attendance_read_routes, create_attendance_write_routes};
pub use attendance_clock_handler::{create_attendance_clock_routes, create_attendance_clock_read_routes, create_attendance_clock_write_routes};
// <<< CUSTOM
// END CUSTOM
